### ISSUE TITLE
Atomic changes are incorrectly carried over during atomic upgrade

### ISSUE THREAD

**Issue by albinkc** [ash-project/ash#1042]
I'm getting a validation error, even though the status in the create response and DB says open (verified manually).

```elixir
  ticket = (  Helpdesk.Support.Ticket  |> Ash.Changeset.for_create(:open, %{subject: "My mouse won't click33!"})  |> Ash.create!())

22:09:03.164 [debug] QUERY OK db=2.4ms idle=1348.9ms
begin []

22:09:03.199 [debug] QUERY OK source="tickets" db=3.0ms
INSERT INTO "tickets" ("id","status","subject") VALUES ($1,$2,$3) RETURNING "status","subject","id" ["b201e6eb-f752-4f0d-b1d3-32013c47f8d0", :open, "My mouse won't click33!"]

22:09:03.204 [debug] QUERY OK db=2.1ms
commit []
#Helpdesk.Support.Ticket<
  __meta__: #Ecto.Schema.Metadata<:loaded, "tickets">,
  id: "b201e6eb-f752-4f0d-b1d3-32013c47f8d0",
  subject: "My mouse won't click33!",
  status: :open,
  aggregates: %{},
  calculations: %{},
  ...
>
iex(2)> ticket|> Ash.Changeset.for_update(:close)|> Ash.update!()
** (Ash.Error.Invalid) Invalid Error

* Invalid value provided for status: Ticket is already closed.

"closed"

  (elixir 1.16.2) lib/process.ex:860: Process.info/2
  (ash 3.0.0-rc.27) lib/ash/error/changes/invalid_attribute.ex:5: Ash.Error.Changes.InvalidAttribute.exception/1
  (ash 3.0.0-rc.27) lib/ash/query/function/error.ex:13: Ash.Query.Function.Error.evaluate/1
  (ash 3.0.0-rc.27) lib/ash/filter/runtime.ex:578: Ash.Filter.Runtime.resolve_expr/5
  (ash 3.0.0-rc.27) lib/ash/filter/runtime.ex:231: Ash.Filter.Runtime.do_match/5
  (ash 3.0.0-rc.27) lib/ash/changeset/changeset.ex:2203: anonymous fn/4 in Ash.Changeset.add_atomic_validations/3
  (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
  (elixir 1.16.2) lib/enum.ex:2582: Enum.reduce_while/3
    (elixir 1.16.2) lib/process.ex:860: Process.info/2
    (ash 3.0.0-rc.27) lib/ash/error/invalid.ex:5: Ash.Error.Invalid.exception/1
    (ash 3.0.0-rc.27) /Users/albin/projects/helpdesk/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.0.0-rc.27) lib/ash/error/error.ex:33: Ash.Error.to_error_class/2
    (ash 3.0.0-rc.27) lib/ash/actions/update/bulk.ex:111: Ash.Actions.Update.Bulk.run/6
    (ash 3.0.0-rc.27) lib/ash/actions/update/update.ex:121: Ash.Actions.Update.run/4
    (ash 3.0.0-rc.27) lib/ash.ex:2351: Ash.update/2
    iex:2: (file)
```
My repo with the added extension and migrations: 
https://github.com/albinkc/helpdesk/

Not sure if I missed something

_Originally posted by @albinkc in https://github.com/ash-project/ash_postgres/issues/242#issuecomment-2070268489_

**Comment by zachdaniel** [comment]
Please try main and let me know how it works for you.

**Comment by albinkc** [comment]
Awesome! Everything works as expected now.

# deps:
```elixir
{:ash, git: "https://github.com/ash-project/ash.git", branch: "main", override: true},
{:picosat_elixir, "~> 0.2"},
{:ash_postgres, "~> 2.0.0-rc"}
```

# Create
```elixir
iex(1)> ticket = Helpdesk.Support.Ticket |> Ash.Changeset.for_create(:open, %{subject: "My mouse won't click!999"}) |> Ash.create!()

07:20:27.398 [debug] QUERY OK db=0.9ms idle=1006.9ms
begin []

07:20:27.412 [debug] QUERY OK source="tickets" db=1.0ms
INSERT INTO "tickets" ("id","status","subject") VALUES ($1,$2,$3) RETURNING "status","subject","id" ["2463f931-7e69-4a2b-81ca-8540af89c696", :open, "My mouse won't click!999"]

07:20:27.415 [debug] QUERY OK db=0.3ms
commit []
#Helpdesk.Support.Ticket<
  __meta__: #Ecto.Schema.Metadata<:loaded, "tickets">,
  id: "2463f931-7e69-4a2b-81ca-8540af89c696",
  subject: "My mouse won't click!999",
  status: :open,
  aggregates: %{},
  calculations: %{},
  ...
>
```
# First update
```elixir
iex(2)> ticket |> Ash.Changeset.for_update(:close) |> Ash.update!()

07:21:23.683 [debug] QUERY OK source="tickets" db=17.5ms queue=2.7ms idle=1272.9ms
UPDATE "tickets" AS t0 SET "status" = $1::varchar, "id" = (CASE WHEN t0."status"::varchar = $2::varchar THEN ash_raise_error((jsonb_build_object('exception', $3::text, 'input', jsonb_build_object($4::text, $5::jsonb, $6::text, $7::varchar::varchar, $8::text, $9::jsonb, $10::text, $11::jsonb)))::jsonb, $12::uuid) ELSE t0."id"::uuid END) WHERE (t0."id"::uuid = $13::uuid) RETURNING t0."id", t0."subject", t0."status" [:closed, :closed, "Ash.Error.Changes.InvalidAttribute", "message", "Ticket is already closed", "value", :closed, "vars", %{value: "closed", field: "status"}, "field", "id", nil, "2463f931-7e69-4a2b-81ca-8540af89c696"]
#Helpdesk.Support.Ticket<
  __meta__: #Ecto.Schema.Metadata<:loaded, "tickets">,
  id: "2463f931-7e69-4a2b-81ca-8540af89c696",
  subject: "My mouse won't click!999",
  status: :closed,
  aggregates: %{},
  calculations: %{},
  ...
>
```
# Redundant update
```elixir
iex(3)> ticket |> Ash.Changeset.for_update(:close) |> Ash.update!()

07:21:41.674 [debug] QUERY ERROR source="tickets" db=16.0ms idle=1267.3ms
UPDATE "tickets" AS t0 SET "status" = $1::varchar, "id" = (CASE WHEN t0."status"::varchar = $2::varchar THEN ash_raise_error((jsonb_build_object('exception', $3::text, 'input', jsonb_build_object($4::text, $5::jsonb, $6::text, $7::varchar::varchar, $8::text, $9::jsonb, $10::text, $11::jsonb)))::jsonb, $12::uuid) ELSE t0."id"::uuid END) WHERE (t0."id"::uuid = $13::uuid) RETURNING t0."id", t0."subject", t0."status" [:closed, :closed, "Ash.Error.Changes.InvalidAttribute", "message", "Ticket is already closed", "value", :closed, "vars", %{value: "closed", field: "status"}, "field", "id", nil, "2463f931-7e69-4a2b-81ca-8540af89c696"]
** (Ash.Error.Invalid) Invalid Error

* Invalid value provided for id: Ticket is already closed.

"closed"

  (elixir 1.16.2) lib/process.ex:860: Process.info/2
  (ash 3.0.0-rc.27) lib/ash/error/changes/invalid_attribute.ex:5: Ash.Error.Changes.InvalidAttribute.exception/1
  (ash_postgres 2.0.0-rc.7) lib/data_layer.ex:1959: AshPostgres.DataLayer.handle_raised_error/4
  (ash 3.0.0-rc.27) lib/ash/actions/update/bulk.ex:342: Ash.Actions.Update.Bulk.do_atomic_update/5
  (ash 3.0.0-rc.27) lib/ash/actions/update/bulk.ex:175: Ash.Actions.Update.Bulk.run/6
  (ash 3.0.0-rc.27) lib/ash/actions/update/update.ex:124: Ash.Actions.Update.run/4
  (ash 3.0.0-rc.27) lib/ash.ex:2351: Ash.update/2
  (ash 3.0.0-rc.27) lib/ash.ex:2329: Ash.update!/2
    (elixir 1.16.2) lib/process.ex:860: Process.info/2
    (ash 3.0.0-rc.27) lib/ash/error/invalid.ex:5: Ash.Error.Invalid.exception/1
    (ash 3.0.0-rc.27) /Users/albin/projects/helpdesk/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.0.0-rc.27) lib/ash/error/error.ex:33: Ash.Error.to_error_class/2
    (ash 3.0.0-rc.27) lib/ash/actions/update/bulk.ex:460: Ash.Actions.Update.Bulk.do_atomic_update/5
    (ash 3.0.0-rc.27) lib/ash/actions/update/bulk.ex:175: Ash.Actions.Update.Bulk.run/6
    (ash 3.0.0-rc.27) lib/ash/actions/update/update.ex:124: Ash.Actions.Update.run/4
    iex:3: (file)
```
