### ISSUE TITLE
Ecto.SubQueryError when executing query

### ISSUE THREAD

**Issue by moxley** [ash-project/ash#1134]
I'm getting the following error for a GraphQL query:

```
AshGraphql.Error not implemented for error:
     
     ** (Ash.Error.Unknown) Unknown Error
     
     * ** (Ecto.SubQueryError) the following exception happened when compiling a subquery.
     
         ** (FunctionClauseError) no function clause matching in Access.get/3
     
     The subquery originated from the following query:
     
     from m0 in subquery(from m0 in GF.Members.Member2,
       as: 0,
       join: p1 in ^#Ecto.Query<from p0 in GF.Events.Participation2, as: 0>,
       as: 1,
       on: as(0).id == p1.member_id,
       join: e2 in ^#Ecto.Query<from e0 in GF.Events.Event2, as: 0>,
       as: 2,
       on: as(1).event_id == e2.id,
       join: e3 in ^#Ecto.Query<from e0 in GF.Events.EventTag2, as: 0>,
       as: 3,
       on: as(2).id == e3.event_id,
       join: t4 in ^#Ecto.Query<from t0 in GF.Tags.Tag2, as: 0>,
       as: 4,
       on: t4.id == e3.tag_id,
       where: type(
       as(4).slug,
       {:parameterized, Ash.Type.StringWrapper.EctoType, allow_empty?: false, trim?: true}
     ) ==
       type(
         ^"req1",
         {:parameterized, Ash.Type.StringWrapper.EctoType, allow_empty?: false, trim?: true}
       ),
       where: type(as(0).active, {:parameterized, Ash.Type.Boolean.EctoType, []}) ==
       type(^true, {:parameterized, Ash.Type.Boolean.EctoType, []}),
       where: type(as(0).group_id, {:parameterized, Ash.Type.Integer.EctoType, []}) ==
       type(^362_156, {:parameterized, Ash.Type.Integer.EctoType, []}),
       windows: [order: [order_by: [desc: as(0).joined_group_on]]],
       order_by: [desc: as(0).joined_group_on],
       distinct: [asc: m0.id],
       select: merge(
       merge(struct(m0, [:joined_group_on, :id]), %{
         calculations: %{
           calculation_0:
             type(
               type(
                 type(^true, {:parameterized, Ash.Type.Boolean.EctoType, []}),
                 {:parameterized, Ash.Type.Boolean.EctoType, []}
               ),
               :boolean
             )
         }
       }),
       %{__order__: over(row_number(), :order)}
     )),
       order_by: [asc: m0.__order__],
       limit: ^200,
       select: m0
     
       (ecto 3.11.2) lib/ecto/repo/queryable.ex:214: Ecto.Repo.Queryable.execute/4
       (ecto 3.11.2) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
       (ash_postgres 1.5.25) lib/data_layer.ex:701: anonymous fn/3 in AshPostgres.DataLayer.run_query/2
       (ash_postgres 1.5.25) lib/data_layer.ex:700: AshPostgres.DataLayer.run_query/2
       (ash 2.21.14) lib/ash/actions/read/read.ex:1996: Ash.Actions.Read.run_query/4
       (ash 2.21.14) lib/ash/actions/read/read.ex:407: anonymous fn/5 in Ash.Actions.Read.do_read/4
       (ash 2.21.14) lib/ash/actions/read/read.ex:537: Ash.Actions.Read.maybe_in_transaction/3
       (ash 2.21.14) lib/ash/actions/read/read.ex:227: Ash.Actions.Read.do_run/3
       (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
       (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
       (groupflow 0.1.1) lib/gf/ash/api.ex:1: GF.Ash.Api.read/2
       (ash_graphql 0.28.1) lib/graphql/resolver.ex:447: AshGraphql.Graphql.Resolver.resolve/2
       (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:234: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
       (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:189: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
       (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:174: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
         (elixir 1.16.1) lib/process.ex:860: Process.info/2
         (ash 2.21.14) lib/ash/error/exception.ex:59: Ash.Error.Unknown."exception (overridable 2)"/1
         (ash 2.21.14) lib/ash/error/error.ex:602: Ash.Error.choose_error/2
         (ash 2.21.14) lib/ash/error/error.ex:260: Ash.Error.to_error_class/2
         (ash 2.21.14) lib/ash/actions/read/read.ex:292: Ash.Actions.Read.do_run/3
         (ash 2.21.14) lib/ash/actions/read/read.ex:50: anonymous fn/3 in Ash.Actions.Read.run/3
         (ash 2.21.14) lib/ash/actions/read/read.ex:49: Ash.Actions.Read.run/3
         (groupflow 0.1.1) lib/gf/ash/api.ex:1: GF.Ash.Api.read/2
         (ash_graphql 0.28.1) lib/graphql/resolver.ex:447: AshGraphql.Graphql.Resolver.resolve/2
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:234: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:189: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:174: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:145: Absinthe.Phase.Document.Execution.Resolution.resolve_fields/4
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
         (absinthe 1.7.6) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
         (absinthe 1.7.6) lib/absinthe/pipeline.ex:408: Absinthe.Pipeline.run_phase/3
         (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
         (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
         (phoenix 1.7.12) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2
```

This started happening after upgrading ash and ash_graphql and ash_postgres. It's not yet clear which version and which package was responsible for the change.

I don't know if this is ash_graphql, or just ash. I'm unable to reproduce it outside of GraphQL. I suspect it has something to do with the `:select` part of the Ash.Query. Does ash_graphql set that value?

I logged this Ash.Query returned from the action's `prepare`:

```elixir
#Ash.Query<
  resource: GF.Members.Member2,
  tenant: 362155,
  arguments: %{custom_query_id: "2622"},
  filter: #Ash.Filter<participations.event.tags.slug == "req1" and active == true>,
  sort: [joined_group_on: :desc],
  limit: 200,
  select: [:joined_group_on, :id]
>
```

I was able to convert that to an Ecto.Query and execute it, and there were no errors, so the Ash.Query that resulted in the error must have been further downstream.

The error only happens when the following are all part of the query:

- `participations.event.tags.slug == "req1"`
-  The `:select` contains `:joined_group_on`
- `:joined_group_on` is referenced in the `:sort`.

This error originally happened when the action was using a `modify_query` to build the query from the Ecto version of the query. I rewrote it to pure Ash.Query, hoping that would solve the problem, but it didn't.

Versions:

- ash_graphql 0.28.1
- ash v2.21.14
- ash_postgres 1.5.25

**Comment by zachdaniel** [comment]
Okay, I've just pushed up a fix in df481e56ebcf665e40cc4e74d09b7c7142ef7d41. A simple typo causing a bunch more crap inside of queries than necessary 🤦 Please try out the `2.0` branch and let me know if it resolve your issue. If so, I'll cut a release.

This fixes what *may* cause the issue, but I'm not entirely sure it addresses the root cause. I'll close for now, but please reopen if the issue persists.

**Comment by moxley** [comment]
It works! Thank you so much!

**Comment by zachdaniel** [comment]
🥳 awesome, thanks for tracking down the root of the issue. I have a feeling this issue will rear its head again at some point, but at least you're unblocked!
