### ISSUE TITLE
Sorting by relationship calculation crashes

### ISSUE THREAD

**Issue by torepettersen** [ash-project/ash#1141]
**Describe the bug**
I tried upgrading from ash 2.X to 3.X and now I am not able to sort relationships by calcuations anymore. It used to work in 2.X.

**To Reproduce**
Add calculation to a resource:
```elixir
defmodule Job do
  # ..
  calculations do
    calculate :state_order,
              :integer,
              expr(
                fragment(
                  "array_position(ARRAY['new', 'open', 'closed']::varchar[], ?)",
                  state
                )
              )
  end
end 
```

Sort by the calculation in a related resource:
```elixir
defmodule Company do
  # ..
  relationships do
    has_many :jobs, Job do
      sort [:state_order, :inserted_at]
    end
  end
end
```

Error thrown:
```elixir
[error] ** (MatchError) no match of right hand side value: {:error, [%Spark.Options.ValidationError{message: "invalid value for :source_context option: expected map, got: nil", key: :source_context, value: nil, keys_pa
th: []}]}
    (ash 3.0.0-rc.46) lib/ash/actions/read/relationships.ex:941: Ash.Actions.Read.Relationships.has_parent_expr?/1
    (ash 3.0.0-rc.46) lib/ash/actions/read/relationships.ex:909: Ash.Actions.Read.Relationships.lateral_join?/3
    (ash 3.0.0-rc.46) lib/ash/actions/read/relationships.ex:163: Ash.Actions.Read.Relationships.with_lateral_join_query/4
    (ash 3.0.0-rc.46) lib/ash/actions/read/relationships.ex:152: Ash.Actions.Read.Relationships.related_query/4
    (elixir 1.16.2) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
    (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.2) lib/stream.ex:1828: Enumerable.Stream.do_each/4
    (elixir 1.16.2) lib/enum.ex:4396: Enum.map/2
    (ash 3.0.0-rc.46) lib/ash/actions/read/relationships.ex:43: Ash.Actions.Read.Relationships.fetch_related_records/2
    (ash 3.0.0-rc.46) lib/ash/actions/read/relationships.ex:24: Ash.Actions.Read.Relationships.load/3
    (ash 3.0.0-rc.46) lib/ash/actions/read/read.ex:272: Ash.Actions.Read.do_run/3
    (ash 3.0.0-rc.46) lib/ash/actions/read/read.ex:66: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 3.0.0-rc.46) lib/ash/actions/read/read.ex:65: Ash.Actions.Read.run/3
    (ash 3.0.0-rc.46) lib/ash.ex:1690: Ash.load/3
    (ash 3.0.0-rc.46) lib/ash.ex:1660: Ash.load/3
    (ash 3.0.0-rc.46) lib/ash.ex:1608: Ash.load!/3
    (fox 0.1.0) lib/fox_web/pages/company_live.ex:16: FoxWeb.CompanyLive.mount/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/utils.ex:354: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
    (telemetry 1.2.1) /home/tore/workspace/fox/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
    (phoenix_live_view 0.20.14) lib/phoenix_live_view/static.ex:281: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
```

**Expected behavior**
I expect to not see this error and that the realation would be sorted by the specified calculation.

**Runtime**
 - Elixir version: 1.16.2
 - Erlang version: 26.2.3
 - OS: EndeavourOS
 - Ash version: 3.0.0-rc.46
 - Ash Postgres: 2.0.0-rc.15

**Comment by zachdaniel** [comment]
Thanks for the heads up! I'll push a fix to `main`, let me know if that resolves the issue.

**Comment by torepettersen** [comment]
Thanks :heart:  Yes that worked!
