### ISSUE TITLE
List of atomics in validation results in a pattern match error

### ISSUE THREAD

**Issue by danielatdpg** [ash-project/ash#1194]
**Describe the bug**
Hey, question, I've the following set of changes running for all actions
```elixir
changes do
...
    change set_attribute(:publication_status, :published) do
      only_when_valid? true

      where [
        negate(attribute_equals(:published_at, nil)),
        compare(:published_at,
          greater_than_or_equal_to: &DateTime.utc_now/0
        )
      ]
    end
...
```

When running the primary update action for that resource I get this error
```
** (Ash.Error.Unknown) Unknown Error

     * %CaseClauseError{term: [{:atomic, [:published_at], {:_atomic_ref, :published_at} < ~U[2024-05-22 13:56:17.075341Z], error(Ash.Error.Changes.InvalidAttribute,  %{message: "must be greater than or equal to %{greater_than_or_equal_to}", value: {:_atomic_ref, :published_at}, vars: %{field: :published_at, greater_than_or_equal_to: ~U[2024-05-22 13:56:17.075346Z]}, field: :published_at})}]}
       (ash 3.0.2) lib/ash/changeset/changeset.ex:882: anonymous fn/4 in Ash.Changeset.atomic_condition/3
       (elixir 1.16.2) lib/enum.ex:4839: Enumerable.List.reduce/3
       (elixir 1.16.2) lib/enum.ex:2582: Enum.reduce_while/3
       (ash 3.0.2) lib/ash/changeset/changeset.ex:810: Ash.Changeset.run_atomic_change/3
       (ash 3.0.2) lib/ash/changeset/changeset.ex:693: anonymous fn/3 in ...
```

**To Reproduce**
Create a resource like this
```elixir
defmodule A do
  use Ash.Resource,
    domain: As,
    data_layer: AshPostgres.DataLayer

  attributes do
    uuid_primary_key :id, writable?: true, public?: true

    attribute :publication_status, :atom do
      public? true
      allow_nil? false
      default :draft
    end

    attribute :published_at, :utc_datetime_usec, public?: true
 end
 
 changes do
    #See the change above
 end
end
```
Then run an update on a resource of type `A`

**Expected behavior**
The change should only be performed if the constraints for it are met

**Runtime**
 - Elixir version: 1.16.2
 - Erlang version: Erlang/OTP 26
 - OS: OSX 14.5 (23F79)
 - Ash version: 3.0.2

**Comment by danielatdpg** [comment]
Fixed by https://github.com/ash-project/ash/pull/1195
