### ISSUE TITLE
Error when doing a calculation on an aggregate in nested relationship

### ISSUE THREAD

**Issue by TimisRobert** [ash-project/ash#1211]
**Describe the bug**
As discussed on Discord, I'm opening an issue to keep track of this.

**To Reproduce**
```elixir
defmodule Domain do
  use Ash.Domain

  resources do
    resource One
    resource Two
    resource Three
    resource Four
  end
end

defmodule One do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
    attribute :quantity, :integer
  end
end

defmodule Two do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
  end

  relationships do
    has_many :one, One
  end

  aggregates do
    sum :total_quantity, :one, :quantity, default: 0
  end
end

defmodule Three do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
  end

  relationships do
    belongs_to :two, Two
  end
end

defmodule Four do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
  end

  relationships do
    has_many :three, Three
  end

  calculations do
    # This throws
    calculate :total_quantity,
              :integer,
              expr(sum(three.two, field: :total_quantity))

    # This works
    calculate :total_quantity,
              :integer,
              expr(sum(three.two.one, field: :quantity))
  end
end
```

Then load :total_quantity on Four

**Expected behavior**
To not throw

**Runtime**
 - Elixir version 1.16
 - Erlang version Erlang/OTP 26 [erts-14.2.5]
 - OS NixOS
 - Ash version main branch
 - any related extension versions

**Additional context**

The error thrown:
```
[error] an exception was raised:
    ** (ArgumentError) `nil` is not a Spark DSL module.

        nil.entities([:actions])
        (spark 2.1.22) lib/spark/dsl/extension.ex:171: Spark.Dsl.Extension.get_entities/2
        (ash 3.0.8) lib/ash/resource/info.ex:556: Ash.Resource.Info.primary_action/2
        (ash 3.0.8) lib/ash/resource/info.ex:542: Ash.Resource.Info.primary_action!/2
        (ash 3.0.8) lib/ash/actions/read/read.ex:2816: Ash.Actions.Read.aggregate_field_with_related_filters/7
        (ash 3.0.8) lib/ash/actions/read/read.ex:2657: Ash.Actions.Read.authorize_aggregate/7
        (ash 3.0.8) lib/ash/filter/filter.ex:1314: Ash.Filter.update_aggregates/4
        (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
        (ash 3.0.8) lib/ash/filter/filter.ex:1307: Ash.Filter.update_aggregates/4
        (ash 3.0.8) lib/ash/actions/read/read.ex:2496: anonymous fn/8 in Ash.Actions.Read.authorize_calculation_expressions/8
        (elixir 1.16.3) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
        (ash 3.0.8) lib/ash/actions/read/read.ex:370: anonymous fn/5 in Ash.Actions.Read.do_read/4
        (ash 3.0.8) lib/ash/process_helpers.ex:38: anonymous fn/4 in Ash.ProcessHelpers.async/2
        (elixir 1.16.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
        (elixir 1.16.3) lib/task/supervised.ex:36: Task.Supervised.reply/4
        (ash 3.0.8) lib/ash/process_helpers.ex:32: Ash.ProcessHelpers.async/2
        (ash 3.0.8) lib/ash/process_helpers.ex:67: Ash.ProcessHelpers.task_with_timeout/5
        (ash 3.0.8) lib/ash/actions/read/read.ex:767: Ash.Actions.Read.maybe_in_transaction/3
        (ash 3.0.8) lib/ash/actions/read/read.ex:246: Ash.Actions.Read.do_run/3
        (ash 3.0.8) lib/ash/actions/read/read.ex:66: anonymous fn/3 in Ash.Actions.Read.run/3
```

**Comment by zachdaniel** [comment]
Fixed in https://github.com/ash-project/ash/commit/fbcafa1bfa07e577d3654403fd2b22deb9ea3bf7
