### ISSUE TITLE
Error thrown if relationship aggregate is used in update with atomic_update

### ISSUE THREAD

**Issue by TimisRobert** [ash-project/ash#1213]
**Describe the bug**
 As discussed on Discord, I'm opening an issue to keep track of this.

**To Reproduce**
```elixir
defmodule Domain do
  use Ash.Domain

  resources do
    resource One
    resource Two
    resource Three
  end
end

defmodule One do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
    attribute :quantity, :integer
  end
end

defmodule Two do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
  end

  relationships do
    has_many :one, One
  end

  aggregates do
    sum :total_quantity, :one, :quantity, default: 0
  end
end

defmodule Three do
  use Ash.Resource,
    data_layer: AshPostgres.DataLayer,
    domain: Domain

  attributes do
    uuid_primary_key :id
    attribute :total_quantity, :integer
  end

  relationships do
    belongs_to :two, Two
  end

  actions do
    update :update do
      require_atomic? false

      change atomic_update(:total_quantity, expr(two.total_quantity))
    end
  end
end
```

**Expected behavior**
To not throw

**Runtime**
 - Elixir version 1.16
 - Erlang version Erlang/OTP 26 [erts-14.2.5]
 - OS NixOS
 - Ash version main branch
 - any related extension versions

**Additional context**
```
** (KeyError) key :actor not found in: %{}
    (ash_sql 0.2.0) lib/aggregate.ex:723: anonymous fn/5 in AshSql.Aggregate.maybe_filter_subquery/6
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_sql 0.2.0) lib/aggregate.ex:312: anonymous fn/10 in AshSql.Aggregate.add_aggregates/6
    (ash_sql 0.2.0) lib/join.ex:250: AshSql.Join.related_subquery/3
    (ash_sql 0.2.0) lib/aggregate.ex:159: anonymous fn/7 in AshSql.Aggregate.add_aggregates/6
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_sql 0.2.0) lib/aggregate.ex:88: AshSql.Aggregate.add_aggregates/6
    (ash_sql 0.2.0) lib/join.ex:151: anonymous fn/10 in AshSql.Join.join_all_relationships/10
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_postgres 2.0.6) lib/data_layer.ex:1441: anonymous fn/3 in AshPostgres.DataLayer.bulk_updatable_query/6
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
    (ash_postgres 2.0.6) lib/data_layer.ex:1436: AshPostgres.DataLayer.bulk_updatable_query/6
    (ash_postgres 2.0.6) lib/data_layer.ex:2671: AshPostgres.DataLayer.update/2
    (ash 3.0.8) lib/ash/actions/update/bulk.ex:2046: anonymous fn/5 in Ash.Actions.Update.Bulk.run_batch/10
    (elixir 1.16.3) lib/enum.ex:4839: Enumerable.List.reduce/3
    (elixir 1.16.3) lib/enum.ex:2582: Enum.reduce_while/3
```

**Comment by zachdaniel** [comment]
I linked the fix to the wrong issue.
