### ISSUE TITLE
(`ash.gen` igniters) Better error message if required arguments are not provided

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#1349]
**Describe the bug**

At the moment, calling `ash.gen.resource` with no arguments at all raises a FunctionClauseError:

```
$ mix ash.gen.resource
** (FunctionClauseError) no function clause matching in Mix.Tasks.Ash.Gen.Resource.igniter/2

    The following arguments were given to Mix.Tasks.Ash.Gen.Resource.igniter/2:

        # 1
        %Igniter{rewrite: %Rewrite{sources: %{}, extensions: %{".ex" => Rewrite.Source.Ex, 
".exs" => Rewrite.Source.Ex, "default" => Rewrite.Source}}, issues: [], tasks: [], warnings: [], 
assigns: %{igniter_exs: []}, moves: %{}}

        # 2
        []

    Attempted function clauses (showing 1 out of 1):

        def igniter(igniter, [resource | argv])

    (ash 3.2.6) lib/mix/tasks/gen/ash.gen.resource.ex:60: Mix.Tasks.Ash.Gen.Resource.igniter/2
    (ash 3.2.6) lib/mix/tasks/gen/ash.gen.resource.ex:31: Mix.Tasks.Ash.Gen.Resource.run/1
```

(`ash.gen.domain` with no arguments causes an almost-identical error)

And calling it with options but no resource name generates a different error message:

```
$ mix ash.gen.resource -e postgres
** (ArgumentError) expected an Elixir module, got: Elixir
    (elixir 1.17.2) lib/module.ex:1747: Module.split/2
    (igniter 0.3.9) lib/igniter/code/module.ex:381: Igniter.Code.Module.do_proper_location/2
    (ash 3.2.6) lib/mix/tasks/gen/ash.gen.domain.ex:18: Mix.Tasks.Ash.Gen.Domain.igniter/2
    (ash 3.2.6) lib/mix/tasks/gen/ash.gen.resource.ex:182: Mix.Tasks.Ash.Gen.Resource.igniter/2
```

**Expected behavior**

Clear error messages about what is missing, eg.

```
$ mix ash.gen.resource
Please provide a resource module name. See `mix help ash.gen.resource` for more information

$ mix ash.gen.resource -e postgres 
Please provide a resource module name. See `mix help ash.gen.resource` for more information

$ mix ash.gen.domain
Please provide a domain module name. See `mix help ash.gen.domain` for more information
```

**Runtime**

 - Elixir version 1.17.2-otp-27
 - Erlang version 27.0.1
 - OS macOS Sonoma
 - Ash version 3.2.5
 - Igniter version 0.3.9

**Comment by zachdaniel** [comment]
I will fix this this as part of fixing this: https://github.com/ash-project/igniter/issues/60

We will make the helper for parsing options split out non-flag options as positional arguments and validate their presence, providing an error message.

**Comment by zachdaniel** [comment]
This has been improved in `main`
