### ISSUE TITLE
Error resolving query: key :arguments not found in: nil

### ISSUE THREAD

**Issue by FedeMadoery** [ash-project/ash#1366]
**Describe the bug**
Requesting a set of fields on a mutation throws an error in the calculations.

For example, in my case, I'm doing an update to the `ColleagueChannel`, that has notes. As a result, I request the following fragment:

```
fragment ColleagueChannel on ColleagueChannel {
  id
  notes
  displayName # Calculation that loads the colleague_group internally 
  colleagueGroup { # <-- belongs_to :colleague_group
   id
  }
}
```

Update Action:

```
update :update do
      primary? true
      require_atomic? false

      argument :note, :string do
        description "The shared note."
      end

      change set_attribute(:note, arg(:note))

      #This is a before_action, make sure that you put a before_action to trigger the error (it can be empty, without logic and happens the same thing)
      change MessageOnUpdate do 
        description "Creates message upon note updates"
      end
    end
```
Let me know if need more data to reproduce it, I can do my best to provide more code.

**Expected behavior**
Been able to update the entity and request for any fields as a result of the mutation.

**Runtime**
 - Elixir 1.16.2
 - Erlang/OTP 26 
 - Ash 3.3
 - AshGraphql 1.2

**Additional context**

Stack trace:

```
[error] 34ab3481-94ec-48f4-8c86-d6cf8f5064c1: Exception raised while resolving query.

** (KeyError) key :arguments not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map

    (ash 3.3.1) lib/ash/resource.ex:405: Ash.Resource.loaded?/3
    (elixir 1.16.2) lib/enum.ex:4199: Enum.predicate_list/3
    (ash 3.3.1) lib/ash/actions/read/calculations.ex:1475: Ash.Actions.Read.Calculations.load_depended_on_calc/14
    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash 3.3.1) lib/ash/actions/read/calculations.ex:1241: Ash.Actions.Read.Calculations.load_single_calculation_dependency/13
    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash 3.3.1) lib/ash/actions/read/calculations.ex:1241: Ash.Actions.Read.Calculations.load_single_calculation_dependency/13
    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash 3.3.1) lib/ash/actions/read/calculations.ex:1257: Ash.Actions.Read.Calculations.load_single_calculation_dependency/13
    (elixir 1.16.2) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
    (stdlib 5.2.2) maps.erl:416: :maps.fold_1/4
    (ash 3.3.1) lib/ash/actions/read/calculations.ex:703: Ash.Actions.Read.Calculations.split_and_load_calculations/6
    (ash 3.3.1) lib/ash/actions/read/read.ex:194: Ash.Actions.Read.do_run/3
    (ash 3.3.1) lib/ash/actions/read/read.ex:66: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 3.3.1) lib/ash/actions/read/read.ex:65: Ash.Actions.Read.run/3
    (ash 3.3.1) lib/ash.ex:1736: Ash.load/3
    (ash 3.3.1) lib/ash/actions/update/bulk.ex:2387: Ash.Actions.Update.Bulk.load_data/5
    (ash 3.3.1) lib/ash/actions/update/bulk.ex:2359: Ash.Actions.Update.Bulk.process_results/10
    (ash 3.3.1) lib/ash/actions/update/bulk.ex:1662: Ash.Actions.Update.Bulk.do_handle_batch/13
    (ash 3.3.1) lib/ash/actions/update/bulk.ex:1540: anonymous fn/13 in Ash.Actions.Update.Bulk.handle_batch/10
 ```

**Comment by zachdaniel** [comment]
Fixed in c8e1cddb2b0d24559de51b7bb87e18578f24c253
