### ISSUE TITLE
Error with embedded array attribute

### ISSUE THREAD

**Issue by nallwhy** [ash-project/ash#1372]
**Describe the bug**

Error with embedded array attribute on create

```elixir
defmodule Todo do
  use Ash.Resource, data_layer: :embedded

  attributes do
    attribute :body, :string, allow_nil?: false
  end

  actions do
    defaults [:read, create: [:body], update: [:body]]
  end
end

defmodule Post do
  use Ash.Resource, data_layer: Ash.DataLayer.Ets, domain: Domain

  attributes do
    uuid_primary_key :id
    attribute :title, :string, allow_nil?: false
    attribute :todo_list, {:array, Todo}, allow_nil?: false
  end

  actions do
    defaults create: [:title, :todo_list], update: [:title, :todo_list]
  end
end

Post
|> AshPhoenix.Form.for_create(:create, forms: [auto?: true])
|> to_form()
|> AshPhoenix.Form.add_form([:todo_list, 0])
```

```
    ** (CaseClauseError) no case clause matching: {:ok, %{__struct__: Todo}}
        /Users/json/Library/Caches/mix/installs/elixir-1.17.1-erts-14.2.4/67592b7cf4de677241f7aec395efb13a/deps/ash/lib/ash/embeddable_type.ex:284: anonymous fn/4 in Todo.cast_input_array/2
        (elixir 1.17.1) lib/enum.ex:4858: Enumerable.List.reduce/3
        (elixir 1.17.1) lib/enum.ex:2585: Enum.reduce_while/3
        /Users/json/Library/Caches/mix/installs/elixir-1.17.1-erts-14.2.4/67592b7cf4de677241f7aec395efb13a/deps/ash/lib/ash/embeddable_type.ex:244: Todo.cast_input_array/2
        (ash 3.3.3) lib/ash/changeset/changeset.ex:4889: Ash.Changeset.do_change_attribute/4
        (stdlib 5.2.2) maps.erl:416: :maps.fold_1/4
        (ash 3.3.3) lib/ash/changeset/changeset.ex:1810: Ash.Changeset.handle_params/4
        (ash 3.3.3) lib/ash/changeset/changeset.ex:1692: Ash.Changeset.do_for_action/4
```

**To Reproduce**

https://gist.github.com/nallwhy/b94c87cb6ed1462c61c837def9f76cb8

**Expected behavior**

no error

**Runtime**
 - Elixir version: 1.17.1
 - Erlang version: 26.2.4
 - OS: mac
 - Ash version: a719c791babb7358ce67be0a02e5e6a986a63aaa
 - any related extension versions
   - AshPhoenix: 2.1.1

**Comment by zachdaniel** [comment]
This should be fixed in main. Keep in mind that if you are developing against main you may very easily run into issues given that it is bleeding edge work. Thank you for the report 👍
