### ISSUE TITLE
Error on get started

### ISSUE THREAD

**Issue by manicar2093** [ash-project/ash#1405]
**Describe the bug**
I was trying the Get Started tutorial and I found when I get to the persistance step it fails. I've followed step by step this but a NoDataProvided error raises.

I added Ash.Resource for data layer, recompile, copy/paste the example from page and nothing

```elixir
defmodule Helpdesk.Support.Ticket do
  use Ash.Resource, domain: Helpdesk.Support
  use Ash.Resource,
    domain: Helpdesk.Support,
    data_layer: Ash.DataLayer.Ets

  actions do

    defaults [:read]

    create :open do
      accept [:subject]
    end

    update :close do
      accept []

      validate attribute_does_not_equal(:status, :closed) do
        message "Ticket is already closed"
      end

      change set_attribute(:status, :closed)
    end

  end

  attributes do
    uuid_primary_key :id

    attribute :subject, :string do

      allow_nil? false

      public? true
    end

    attribute :status, :atom do
      constraints [one_of: [:open, :closed]]

      default :open

      allow_nil? false
    end
  end

end

```

Error

```
Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Interactive Elixir (1.17.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> require Ash.Query
Ash.Query
iex(2)> for i <- 0..5 do
...(2)>   ticket =
...(2)>     Helpdesk.Support.Ticket
...(2)>     |> Ash.Changeset.for_create(:open, %{subject: "Issue #{i}"})
...(2)>     |> Ash.create!()
...(2)>
...(2)>   if rem(i, 2) == 0 do
...(2)>     ticket
...(2)>     |> Ash.Changeset.for_update(:close)
...(2)>     |> Ash.update!()
...(2)>   end
...(2)> end
[
  #Helpdesk.Support.Ticket<
    __meta__: #Ecto.Schema.Metadata<:built, "">,
    id: "a68d1e90-d1d9-4b78-9700-5f6db97b9246",
    subject: "Issue 0",
    status: :closed,
    aggregates: %{},
    calculations: %{},
    ...
  >,
  nil,
  #Helpdesk.Support.Ticket<
    __meta__: #Ecto.Schema.Metadata<:built, "">,
    id: "f70970a6-414d-4246-8aa7-71572d9dbbef",
    subject: "Issue 2",
    status: :closed,
    aggregates: %{},
    calculations: %{},
    ...
  >,
  nil,
  #Helpdesk.Support.Ticket<
    __meta__: #Ecto.Schema.Metadata<:built, "">,
    id: "5380ecfd-643b-4b09-b0b4-c4f32b2357f3",
    subject: "Issue 4",
    status: :closed,
    aggregates: %{},
    calculations: %{},
    ...
  >,
  nil
]
iex(3)> Helpdesk.Support.Ticket
Helpdesk.Support.Ticket
iex(4)> |> Ash.Query.filter(contains(subject, "2"))
#Ash.Query<
  resource: Helpdesk.Support.Ticket,
  filter: #Ash.Filter<contains(subject, "2")>
>
iex(5)> |> Ash.read!
** (Ash.Error.Framework) Framework Error

* No data provided to resource Elixir.Helpdesk.Support.Ticket. Perhaps you are missing a call to `Ash.DataLayer.Simple.set_data/2`?.

Another common cause of this is failing to add a data layer for a resource. You can add a data layer like so:

`use Ash.Resource, data_layer: Ash.DataLayer.Ets`

  (elixir 1.17.2) lib/process.ex:864: Process.info/2
  (ash 3.4.1) lib/ash/error/simple_data_layer/no_data_provided.ex:5: Ash.Error.SimpleDataLayer.NoDataProvided.exception/1
  (ash 3.4.1) lib/ash/data_layer/simple/simple.ex:51: Ash.DataLayer.Simple.run_query/2
  (ash 3.4.1) lib/ash/actions/read/read.ex:2485: Ash.Actions.Read.run_query/4
  (ash 3.4.1) lib/ash/actions/read/read.ex:469: anonymous fn/7 in Ash.Actions.Read.do_read/4
  (ash 3.4.1) lib/ash/actions/read/read.ex:826: Ash.Actions.Read.maybe_in_transaction/3
  (ash 3.4.1) lib/ash/actions/read/read.ex:249: Ash.Actions.Read.do_run/3
  (ash 3.4.1) lib/ash/actions/read/read.ex:66: anonymous fn/3 in Ash.Actions.Read.run/3
    (elixir 1.17.2) lib/process.ex:864: Process.info/2
    (ash 3.4.1) lib/ash/error/framework.ex:3: Ash.Error.Framework.exception/1
    (ash 3.4.1) /home/manuel/Development/helpdesk/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.4.1) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
    (ash 3.4.1) lib/ash/actions/read/read.ex:340: anonymous fn/3 in Ash.Actions.Read.do_run/3
    (ash 3.4.1) lib/ash/actions/read/read.ex:265: Ash.Actions.Read.do_run/3
    (ash 3.4.1) lib/ash/actions/read/read.ex:66: anonymous fn/3 in Ash.Actions.Read.run/3
    iex:5: (file)
iex(5)>
```

**To Reproduce**
Follow Get Started tutorial until [Adding basic persistance](https://ash-hq.org/docs/guides/ash/latest/tutorials/get-started#adding-basic-persistence) section

**Expected behavior**
Not to failed and continue with tutorial

**Runtime**
 - Elixir version: Elixir 1.17.2 (compiled with Erlang/OTP 27)
 - Erlang version: Erlang/OTP 27 [erts-15.0.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
 - OS: Ubuntu 20.04
 - Ash version: {:ash, "~> 3.0"}
 - any related extension versions

**Additional context**

**Comment by zachdaniel** [comment]
Did you try restarting your iex session?

**Comment by zachdaniel** [comment]
I can't reproduce the issue, so will need more info to continue.
