### ISSUE TITLE
Error seeding data after upgrading to ash_postgres 2.4.0

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#1465]
**Describe the bug**

We might be doing something odd with seeds, but dependabot picked this up when auto-updating ash_postgres today. It worked with ash_postgres 2.3.1!

```
  9) test create/1 it creates a snapshot of the operation (MyApp.OperationExecutionTest)
     test/my_app/operation_execution/operation_execution_test.exs:106
     ** (Ash.Error.Unknown) Unknown Error

     * ** (Ecto.QueryError) at least one field must be selected for binding `0`, got an empty list in query:

     from e0 in MyApp.ElementContext,
       as: 0,
       where: e0.id == ^...,
       update: [set: [segment_id: ^...]],
       select: struct(e0, [])

       (ecto 3.12.3) lib/ecto/repo/queryable.ex:214: Ecto.Repo.Queryable.execute/4
       (ash_postgres 2.4.0) lib/data_layer.ex:1389: AshPostgres.DataLayer.update_query/4
       (ash_postgres 2.4.0) lib/data_layer.ex:2758: AshPostgres.DataLayer.update/2
       (ash 3.4.14) lib/ash/seed.ex:309: Ash.Seed.update_or_seed!/4
       (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
       (ash 3.4.14) lib/ash/seed.ex:232: anonymous fn/7 in Ash.Seed.change_relationships/2
       (ash 3.4.14) lib/ash/changeset/changeset.ex:3761: anonymous fn/2 in Ash.Changeset.run_after_actions/3
       (elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
       (elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
       (ash 3.4.14) lib/ash/seed.ex:211: anonymous fn/7 in Ash.Seed.change_relationships/2
       (ash 3.4.14) lib/ash/changeset/changeset.ex:3380: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
       (ash 3.4.14) lib/ash/changeset/changeset.ex:3290: Ash.Changeset.with_hooks/3
       (ash 3.4.14) lib/ash/seed.ex:135: Ash.Seed.seed!/3
     code: segment = insert(:segment, element_contexts: [element_context])
     stacktrace:
       (as above)
```

This project uses ex_machina with Ash.Seed, and this test (and a handful of others with the same error) are attempting to build a chain of records like so: 

```elixir
      element_version = insert(:element_version)
      element_context = insert(:element_context, element_version: element_version)
      segment = insert(:segment, element_contexts: [element_context])
```

The element_context belongs to a segment, so it would have been created with a different segment and is then being assigned to a new one. I can clean up the code a bit because its a bit silly to do it that way, but the error still shouldn't happen I think!

**Expected behavior**

The seed data to be inserted correctly into the database, and the test to run without error as it did with previous versions of ash_postgres.

**Runtime**

 - Elixir version 1.15.4-otp-26
 - Erlang version 26.0.2
 - OS macOS Sonoma
 - Ash version 3.4.14
 - AshPostgres 2.4.0

**Comment by zachdaniel** [comment]
@sevenseacat I was wrong, sorry. An additional fix in `ash` was required.
