### ISSUE TITLE
Default values not applied with bulk updates

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash#1530]
**Describe the bug**
When running a bulk update with an action that provides a default for an argument, the value of that argument appears to be `nil`.

**To Reproduce**
Create a resource with a `:datetime` attribute.

```elixir
  attributes do
    uuid_primary_key :id
    attribute :title, :string, allow_nil?: false
    attribute :description, :string
    attribute :expires, :datetime, allow_nil?: false
  end
```

And an update action,
```elixir
    update :expire do
      argument :date, :datetime, default: &DateTime.utc_now/0
      change atomic_update(:expires, expr(^arg(:date)))
    end
```

Then use a this action in a bulk update.
```elixir
    Ash.Generator.action_input(Classified, :create)
    |> Enum.take(10)
    |> Ash.bulk_create!(Classified, :create)

    Classified
    |> Ash.Query.limit(5)
    |> Ash.bulk_update!(:expire, %{}, stop_on_error?: true)
```

Full minimal reproduction project: https://github.com/aidalgol/ash_bug_repro
Run `mix test` in this project.

<details>
<summary>console output</summary>

```console
11:14:05.724 [debug] QUERY OK db=2.9ms
begin []

11:14:05.742 [debug] QUERY OK source="classifieds" db=5.2ms
INSERT INTO "classifieds" ("created_at","description","expires","id","title","updated_at") VALUES ($1,$2,$3,$4,$5,$6),($7,DEFAULT,$8,$9,$10,$11),($12,$13,$14,$15,$16,$17),($18,DEFAULT,$19,$20,$21,$22),($23,DEFAULT,$24,$25,$26,$27),($28,$29,$30,$31,$32,$33),($34,DEFAULT,$35,$36,$37,$38),($39,$40,$41,$42,$43,$44),($45,DEFAULT,$46,$47,$48,$49),($50,DEFAULT,$51,$52,$53,$54) [~U[2024-10-17 22:14:05.643099Z], nil, ~U[2024-10-17 22:14:05Z], "9997a36e-c89e-4ad8-85cf-33c0b2449606", "񟊋򺭆𻼈󼧫򽹬񠳹񵤡ི򐲫", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05Z], "ebec70ec-e1e1-4981-91a8-408e66300895", "򛢍󋛅򞽠𿻙𑊦𙋷񟭵񅁀", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], "񕌮󖸅𷖉򳘸􁡂񏞳", ~U[2024-10-17 22:14:05Z], "4b5b060b-410d-4d10-ace6-1f8e64651f5e", "񤼋񌎻񵋁", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05Z], "942a2696-f221-4729-96ab-0755fb8a4364", "񂧱󯾢󚟣􍽼", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05Z], "188b8d57-7e2e-418b-b3d0-1782bb8abd61", "𓭈𧐚񁞿򨸗", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], nil, ~U[2024-10-17 22:14:05Z], "b6201ace-84db-422c-bf08-8e486fb90372", "󸺠࠭", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05Z], "81dd269a-723d-406f-8d41-149d8c0cce3b", "񩀡𷝐򘦂", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], "𥽁", ~U[2024-10-1722:14:05Z], "1ad54fa0-3a2f-46a7-a8f2-5cdec7b1026c", "􂋻񟠬", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05Z], "e29631eb-32e6-4e72-806b-7c74881687f4", "󚿎󍊯", ~U[2024-10-17 22:14:05.643099Z], ~U[2024-10-17 22:14:05.643099Z], ...]

11:14:05.742 [debug] QUERY OK db=0.1ms
commit []

11:14:05.786 [debug] QUERY ERROR source="classifieds" db=5.7ms queue=1.2ms
UPDATE "classifieds" AS c0 SET "expires" = s1."__new_expires", "updated_at" = s1."__new_updated_at" FROM (SELECT $1::timestamp::timestamp AS "__new_updated_at", (CASE WHEN (NULL::timestamp + ($2::bigint::numeric * interval '1 week')) IS NULL THEN ash_raise_error($3::jsonb, NULL::timestamp) ELSE (NULL::timestamp + ($4::bigint::numeric * interval '1 week')) END)::timestamp AS "__new_expires", sc0."id" AS "id" FROM "classifieds" AS sc0 LIMIT $5) AS s1 WHERE (c0."id" = s1."id") [~U[2024-10-17 22:14:05.751719Z], 4, "{\"exception\":\"Ash.Error.Changes.Required\",\"input\":{\"field\":\"expires\",\"resource\":\"Elixir.Hello.Market.Classified\",\"type\":\"attribute\"}}", 4, 5]


1) test boom (Hello.Market.ClassifiedTest)
test/hello/market/classified_test.exs:6
** (Ash.Error.Invalid) Invalid Error

* attribute expires is required
(elixir 1.17.3) lib/process.ex:864: Process.info/2
(ash 3.4.29) lib/ash/error/changes/required.ex:4: Ash.Error.Changes.Required.exception/1
(ash_postgres 2.4.8) lib/data_layer.ex:2177: AshPostgres.DataLayer.handle_raised_error/4
(ash 3.4.29) lib/ash/actions/update/bulk.ex:533: Ash.Actions.Update.Bulk.do_atomic_update/5
(ash 3.4.29) lib/ash/actions/update/bulk.ex:263: Ash.Actions.Update.Bulk.run/6
(ash 3.4.29) lib/ash.ex:2390: Ash.bulk_update!/4
test/hello/market/classified_test.exs:13: Hello.Market.ClassifiedTest."test boom"/1
(ex_unit 1.17.3) lib/ex_unit/runner.ex:485: ExUnit.Runner.exec_test/2
(stdlib 4.3.1.4) timer.erl:235: :timer.tc/1
(ex_unit 1.17.3) lib/ex_unit/runner.ex:407: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
code: |> Ash.bulk_update!(:renew, %{period: 4}, stop_on_error?: true)
stacktrace:
(ash 3.4.29) lib/ash.ex:2409: Ash.bulk_update!/4
test/hello/market/classified_test.exs:13: (test)
```

</details>

**Expected behavior**
The bulk update argument `:date` should have the default value.

**Runtime**
Erlang/OTP 25 [erts-13.2.2.10] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

IEx 1.17.3 (compiled with Erlang/OTP 25)

NixOS

**Additional context**
N/A

**Comment by zachdaniel** [comment]
The test on that example project pass for me using main of ash and ash_postgres, so I assume that this has been fixed :)
