### ISSUE TITLE
Error using constraints on a calculation

### ISSUE THREAD

**Issue by aidalgol** [ash-project/ash#1534]
**Describe the bug**
Using `constraints: [one_of: [:foo, :bar]]` on a calculation of type `:atom` raises an error when running the calculation.

**To Reproduce**
Define a resource with a `:datetime` attribute.
```elixir
  attributes do
    uuid_primary_key :id
    attribute :title, :string, allow_nil?: false
    attribute :description, :string
    attribute :expires, :datetime
  end
```
Define a calculation that returns a different atom based on the value of that attribute.
```elixir
    calculate :status, :atom, constraints: [one_of: [:new, :expired, :active]] do
      expr(
        cond do
          is_nil(expires) -> :new
          expires <= now() -> :expired
          true -> :active
        end
      )
    end
```

Minimal reproduction project: https://github.com/aidalgol/ash_bug_repro/tree/calculation_constraints_bug
Run `mix test`

<details>
<summary>console output</summary>

```console
13:33:03.964 [debug] QUERY OK db=5.0ms
begin []

13:33:03.992 [debug] QUERY OK source="classifieds" db=9.8ms
INSERT INTO "classifieds" ("expires","id","title") VALUES ($1,$2,$3) RETURNING "expires","description","title","id" [~U[2024-10-19 00:33:03Z], "25c8ee94-029d-4eba-8855-8eb4fb4ad3ec", "foo"]

13:33:04.000 [debug] QUERY OK db=0.2ms
commit []


1) test boom (Hello.Market.ClassifiedTest)
test/hello/market/classified_test.exs:6
** (Ash.Error.Unknown) Unknown Error

* ** (Ecto.QueryError) deps/ash_postgres/lib/data_layer.ex:2920: invalid keyword list in query:

from c0 in Hello.Market.Classified,
as: 0,
where: type(as(0).id, {:parameterized, {Ash.Type.UUID.EctoType, []}}) ==
type(^"25c8ee94-029d-4eba-8855-8eb4fb4ad3ec", {:parameterized, {Ash.Type.UUID.EctoType, []}}),
select: merge(struct(c0, [:id]), %{
status:
type(
type(
type(
^[{:constraints, one_of: [:new, :expired, :active]}],
{:parameterized, {Ash.Type.Atom.EctoType, []}}
),
{:parameterized, {Ash.Type.Atom.EctoType, []}}
),
{:parameterized, {Ash.Type.Atom.EctoType, []}}
)
})

keyword lists are only allowed at the top level of where, having, distinct, order_by, update or a join's on

(elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
(elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/3-lists^foldl/2-0-"/3
(ecto 3.12.4) lib/ecto/repo/queryable.ex:214: Ecto.Repo.Queryable.execute/4
(ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
(ash_postgres 2.4.9) lib/data_layer.ex:771: anonymous fn/3 in AshPostgres.DataLayer.run_query/2
(ash_postgres 2.4.9) lib/data_layer.ex:769: AshPostgres.DataLayer.run_query/2
(ash 3.4.33) lib/ash/actions/read/read.ex:2683: Ash.Actions.Read.run_query/4
(ash 3.4.33) lib/ash/actions/read/read.ex:1066: Ash.Actions.Read.reselect_and_load/6
(ash 3.4.33) lib/ash/actions/read/read.ex:260: Ash.Actions.Read.do_run/3
(ash 3.4.33) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
(ash 3.4.33) lib/ash.ex:1859: Ash.load/3
code: assert Ash.load!(classified, [:status])
stacktrace:
(elixir 1.17.3) lib/process.ex:864: Process.info/2
(ash 3.4.33) lib/ash/error/unknown.ex:3: Ash.Error.Unknown."exception (overridable 2)"/1
(ash 3.4.33) /home/aidan/src/ash_bug_repro/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
(ash 3.4.33) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
(ash 3.4.33) lib/ash/actions/read/read.ex:356: anonymous fn/3 in Ash.Actions.Read.do_run/3
(ash 3.4.33) lib/ash/actions/read/read.ex:285: Ash.Actions.Read.do_run/3
(ash 3.4.33) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
(ash 3.4.33) lib/ash.ex:1859: Ash.load/3
(ash 3.4.33) lib/ash.ex:1813: Ash.load/3
(ash 3.4.33) lib/ash.ex:1754: Ash.load!/3
test/hello/market/classified_test.exs:8: (test)


Finished in 0.2 seconds (0.2s async, 0.00s sync)
1 test, 1 failure
```
</details>

**Expected behavior**
The calculation would return one of the specified atom values.

**Runtime**
```text
Erlang/OTP 25 [erts-13.2.2.10] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

IEx 1.17.3 (compiled with Erlang/OTP 25)
```

See linked repo above for hex package versions.

OS: NixOS 24.11

**Additional context**

**Comment by zachdaniel** [comment]
🤔 I think this is a syntactic issue. Your current constraint will make the calculation expression be ` constraints: [one_of: [:new, :expired, :active]]`

```elixir
    calculate :status, :atom expr(
        cond do
          is_nil(expires) -> :new
          expires <= now() -> :expired
          true -> :active
        end
      ) do
      constraints  constraints: [one_of: [:new, :expired, :active]]
    end
```
