### ISSUE TITLE
Runtime exception when comparing decimals

### ISSUE THREAD

**Issue by Coobaha** [ash-project/ash#1539]
**Describe the bug**
```
** (FunctionClauseError) no function clause matching in Decimal.decimal/1

    The following arguments were given to Decimal.decimal/1:

        # 1
        nil

    (decimal 2.1.1) lib/decimal.ex:1910: Decimal.decimal/1
    (decimal 2.1.1) lib/decimal.ex:386: Decimal.compare/2
    (decimal 2.1.1) lib/decimal.ex:447: Decimal.eq?/2
    (ash 3.4.34) lib/ash/changeset/changeset.ex:5172: Ash.Changeset.do_change_attribute/4
    (stdlib 6.1) maps.erl:860: :maps.fold_1/4
    (ash 3.4.34) lib/ash/changeset/changeset.ex:2022: Ash.Changeset.handle_params/4
    (ash 3.4.34) lib/ash/changeset/changeset.ex:1902: Ash.Changeset.do_for_action/4
    iex:1: (file)
```
Probably Introduced in recent #1532

**To Reproduce**
A minimal set of resource definitions and calls that can reproduce the bug.

**Expected behavior**

**Runtime**
```
  "ash": {:hex, :ash, "3.4.34", "94c3b7bb41d0d67b1a38cdae6bb41b174ae70865b695787a12042569b990304e"
```
**Additional context**

**Comment by zachdaniel** [comment]
Fixed here: https://github.com/ash-project/ash/pull/1538
