### ISSUE TITLE
mix ash.gen.resource fails when parsing multi-letter aliases to options

### ISSUE THREAD

**Issue by albinkc** [ash-project/ash#1540]
-da does not work but -u7 seems to work on its own 
**To Reproduce**

```bash
➜  mix ash.gen.resource Helpdesk.Support.Ticket \
  -da read \
  -u7 id
warning: multi-letter aliases are deprecated, got: :da
  (elixir 1.17.3) lib/option_parser.ex:491: OptionParser.next_with_config/2
  (elixir 1.17.3) lib/option_parser.ex:377: OptionParser.do_parse/6
  (elixir 1.17.3) lib/option_parser.ex:299: OptionParser.parse!/2
  (ash 3.4.34) lib/mix/tasks/gen/ash.gen.resource.ex:37: Mix.Tasks.Ash.Gen.Resource.run/1
  (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2

warning: multi-letter aliases are deprecated, got: :u7
  (elixir 1.17.3) lib/option_parser.ex:491: OptionParser.next_with_config/2
  (elixir 1.17.3) lib/option_parser.ex:377: OptionParser.do_parse/6
  (elixir 1.17.3) lib/option_parser.ex:299: OptionParser.parse!/2
  (ash 3.4.34) lib/mix/tasks/gen/ash.gen.resource.ex:37: Mix.Tasks.Ash.Gen.Resource.run/1
  (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
  (mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2

warning: multi-letter aliases are deprecated, got: :da
  (elixir 1.17.3) lib/option_parser.ex:491: OptionParser.next_with_config/2
  (elixir 1.17.3) lib/option_parser.ex:377: OptionParser.do_parse/6
  (elixir 1.17.3) lib/option_parser.ex:299: OptionParser.parse!/2
  (ash 3.4.34) lib/mix/tasks/gen/ash.gen.resource.ex:77: Mix.Tasks.Ash.Gen.Resource.igniter/2
  (ash 3.4.34) lib/mix/tasks/gen/ash.gen.resource.ex:37: Mix.Tasks.Ash.Gen.Resource.run/1
  (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5

warning: multi-letter aliases are deprecated, got: :u7
  (elixir 1.17.3) lib/option_parser.ex:491: OptionParser.next_with_config/2
  (elixir 1.17.3) lib/option_parser.ex:377: OptionParser.do_parse/6
  (elixir 1.17.3) lib/option_parser.ex:299: OptionParser.parse!/2
  (ash 3.4.34) lib/mix/tasks/gen/ash.gen.resource.ex:77: Mix.Tasks.Ash.Gen.Resource.igniter/2
  (ash 3.4.34) lib/mix/tasks/gen/ash.gen.resource.ex:37: Mix.Tasks.Ash.Gen.Resource.run/1
  (mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5

** (Mix) Could not invoke task "ash.gen.resource": 1 error found!
-da : Missing argument of type keep
```

** Runtime **

Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit]

Elixir 1.17.3 (compiled with Erlang/OTP 27)
- OS: Mac 15
- Igniter version: 0.3.67
- ash 3.4.34

**Comment by zachdaniel** [comment]
TIL that multi-letter aliases are deprecated 😢 Those aliases will just ned to be removed for now.
