### ISSUE TITLE
Malformed SQL generated involving AshGraphql filters, action policies, and field policies

### ISSUE THREAD

**Issue by moxley** [ash-project/ash#1554]
**Describe the bug**

After a recent upgrade of `ash`, `ash_postgres`, and `ash_graphql`, a Postgrex error began to occur when executing an AshGraphql query with a specific style of filter argument, and a specific column attribute is being queried by both an action policy and field policy.

```
** (Ash.Error.Unknown) Unknown Error

* ** (DBConnection.EncodeError) Postgrex expected a boolean, got "active". Please make sure the value you are passing matches the definition in your table or in your query or convert the value accordingly.
  (postgrex 0.19.1) lib/postgrex/type_module.ex:1084: Postgrex.DefaultTypes.encode_list/3
  (postgrex 0.19.1) lib/postgrex/extensions/array.ex:88: Postgrex.Extensions.Array.encode/4
  (postgrex 0.19.1) lib/postgrex/extensions/array.ex:58: Postgrex.Extensions.Array.encode/3
  (postgrex 0.19.1) lib/postgrex/type_module.ex:1084: Postgrex.DefaultTypes.encode_params/3
  (postgrex 0.19.1) lib/postgrex/query.ex:75: DBConnection.Query.Postgrex.Query.encode/3
  (db_connection 2.7.0) lib/db_connection.ex:1449: DBConnection.encode/5
  (db_connection 2.7.0) lib/db_connection.ex:1549: DBConnection.run_prepare_execute/5
  (db_connection 2.7.0) lib/db_connection.ex:1653: DBConnection.run/6
  (db_connection 2.7.0) lib/db_connection.ex:772: DBConnection.parsed_prepare_execute/5
  (db_connection 2.7.0) lib/db_connection.ex:764: DBConnection.prepare_execute/4
  (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:104: Ecto.Adapters.Postgres.Connection.prepare_execute/5
  (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:1002: Ecto.Adapters.SQL.execute!/5
  (ecto_sql 3.12.1) lib/ecto/adapters/sql.ex:994: Ecto.Adapters.SQL.execute/6
  (ecto 3.12.4) lib/ecto/repo/queryable.ex:232: Ecto.Repo.Queryable.execute/4
  (ecto 3.12.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
  (ash_postgres 2.4.9) lib/data_layer.ex:771: anonymous fn/3 in AshPostgres.DataLayer.run_query/2
  (ash_postgres 2.4.9) lib/data_layer.ex:769: AshPostgres.DataLayer.run_query/2
  (ash 3.4.35) lib/ash/actions/read/read.ex:2683: Ash.Actions.Read.run_query/4
  (ash 3.4.35) lib/ash/actions/read/read.ex:542: anonymous fn/8 in Ash.Actions.Read.do_read/5
  (ash 3.4.35) lib/ash/actions/read/read.ex:886: Ash.Actions.Read.maybe_in_transaction/3
    (elixir 1.16.1) lib/process.ex:860: Process.info/2
    (ash 3.4.35) lib/ash/error/unknown.ex:3: Ash.Error.Unknown."exception (overridable 2)"/1
    (ash 3.4.35) /Users/moxley/work/ash_playgrounds/one/deps/splode/lib/splode.ex:211: Ash.Error.to_class/2
    (ash 3.4.35) lib/ash/error/error.ex:66: Ash.Error.to_error_class/2
    (ash 3.4.35) lib/ash/actions/read/read.ex:356: Ash.Actions.Read.do_run/3
    (ash 3.4.35) lib/ash/actions/read/read.ex:81: anonymous fn/3 in Ash.Actions.Read.run/3
    (ash 3.4.35) lib/ash/actions/read/read.ex:80: Ash.Actions.Read.run/3
    (ash 3.4.35) lib/ash.ex:1993: Ash.read/2
    (ash_graphql 1.4.1) lib/graphql/resolver.ex:475: AshGraphql.Graphql.Resolver.resolve/2
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:234: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:189: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:174: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:145: Absinthe.Phase.Document.Execution.Resolution.resolve_fields/4
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
    (absinthe 1.7.8) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
    (absinthe 1.7.8) lib/absinthe/pipeline.ex:408: Absinthe.Pipeline.run_phase/3
    (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
    (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
    (phoenix 1.7.14) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2
```

Below is the Ash.Query as it is inspected in a `modify_query()` call in the action. This shows the problem of the Ash.Query.
```elixir
[lib/one/user.ex:55: One.User.modify_query_0_generated_B69472E1F365160567CE3E3DE2BD2803/2]
query #=> #Ash.Query<
  resource: One.User,
  filter: #Ash.Filter<is_public in [:active, :inactive] and is_public>,
  sort: [id: :asc],
  limit: 51,
  select: [:id, :name, :status, :email, :is_public],
  page: [limit: 50]
>
```

Above, `is_public in [:active, :inactive]` makes no sense. `is_public` is a boolean attribute, and `[:active, :inactive]` are enum values for a different attribute, `:status`.

**To Reproduce**

This example project demonstrates the error:

- [A test](https://github.com/moxley/ash_playground_one/blob/main/test/one_web/graphql/users_test.exs#L81) that executes the AshGraphql query. Note the use of an OR filter. Replacing the OR filter with a simple filter doesn't result in an error.
- [The resource](https://github.com/moxley/ash_playground_one/blob/main/lib/one/user.ex) being queried.
- Note [this action policy](https://github.com/moxley/ash_playground_one/blob/main/lib/one/user.ex#L71) and [this field policy](https://github.com/moxley/ash_playground_one/blob/main/lib/one/user.ex#L83) of the resource both check the same column attribute, `is_public`. After removing this attribute from being considered from either policy, the error goes away.

**Expected behavior**

No error is expected, and the query works.

**Runtime**
 - Elixir version 1.17
 - Erlang version 27.0
 - OS MacOS 14.6.1
 - Ash version 2d463e3 (main)
 - any related extension versions
   - ash_graphql 1.4.1
   - ash_postgres 2.4.11

**Additional context**

**Comment by moxley** [comment]
Thank you, that worked!
