### ISSUE TITLE
Cant access field from has_many relationship

### ISSUE THREAD

**Issue by revati** [ash-project/ash#1574]
**Describe the bug**
Resource has `belongs_to :parent, __MODULE__` relationship and `has_many :ancestors, __MODULE__, manual: Observer.Graph.Node.AncestorsRelationship` relationship that fetches all parents recursively (full code bellow).

Im calling
```elixir
    Observer.Graph.Node
    |> Ash.Query.filter(id in ^ids)
    |> Ash.bulk_update!(:recalculate_relationships, %{}, context ++ [return_errors?: true])
```

Neither 
```elixir
    update :recalculate_relationships do
      change atomic_update(:ancestor_ids, {:atomic, expr(list(ancestors, field: :id))})
    end
```
```
     ** (FunctionClauseError) no function clause matching in AshSql.Aggregate.set_in_group/3

     The following arguments were given to AshSql.Aggregate.set_in_group/3:

         # 1
         #Ecto.Query<from f0 in subquery(from f0 in fragment("?", literal("nodes_0")),
           select: map(f0, [
           :id,
           :title,
           :ancestor_ids,
           :descendant_ids,
           :inserted_at,
           :updated_at,
           :organization_id,
           :parent_id
         ])), where: f0.id in subquery(
           #Ecto.Query<from n0 in Observer.Graph.Node, as: 0, distinct: true, select: n0.id>
         )>

         # 2
         #Ecto.Query<from n0 in Observer.Graph.Node, as: 0, where: type(as(0).organization_id, {:parameterized, {Ash.Type.UUID.EctoType, []}}) ==
           type(^"0192f0f3-52d8-7f67-b52d-6708813927f7", {:parameterized, {Ash.Type.UUID.EctoType, []}}), where: type(as(0).id, {:parameterized, {Ash.Type.UUIDv7.EctoType, []}}) in type(
           ^["0192f0f3-5300-7530-8142-ea8e6dae49eb", "0192f0f3-5309-7a4d-bbb6-2e01dc0a30fc"],
           {:array, {:parameterized, {Ash.Type.UUIDv7.EctoType, []}}}
         )>

         # 3
         Observer.Graph.Node

     Attempted function clauses (showing 2 out of 2):

         defp set_in_group(%{__ash_bindings__: _} = query, _, _resource)
         defp set_in_group(%Ecto.SubQuery{} = subquery, query, resource)
```
nor
```elixir
    update :recalculate_relationships do
      change atomic_update(:ancestor_ids, {:atomic, expr(ancestors.id)})
    end
```
```
     ** (Ash.Error.Unknown) Unknown Error

     * ** (FunctionClauseError) no function clause matching in Ecto.Adapters.Postgres.Connection.quote_name/1
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:1915: Ecto.Adapters.Postgres.Connection.quote_name(#Ecto.Query<from f0 in fragment("?", literal("nodes_1")), select: map(f0, [
       :id,
       :title,
       :ancestor_ids,
       :descendant_ids,
       :inserted_at,
       :updated_at,
       :organization_id,
       :parent_id
     ])>)
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:602: Ecto.Adapters.Postgres.Connection.cte_expr/3
       (elixir 1.17.3) lib/enum.ex:4405: Enum.map_intersperse_list/3
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:586: Ecto.Adapters.Postgres.Connection.cte/2
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:177: Ecto.Adapters.Postgres.Connection.all/2
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:970: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:1885: Ecto.Adapters.Postgres.Connection.get_source/4
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:747: anonymous fn/3 in Ecto.Adapters.Postgres.Connection.join/2
       (elixir 1.17.3) lib/enum.ex:4405: Enum.map_intersperse_list/3
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:735: Ecto.Adapters.Postgres.Connection.join/2
       (ecto_sql 3.12.1) lib/ecto/adapters/postgres/connection.ex:180: Ecto.Adapters.Postgres.Connection.all/2
...
```
works.

## Full code
```elixir
defmodule Observer.Graph.Node do
  use Ash.Resource,
    otp_app: :observer,
    domain: Observer.Graph,
    data_layer: AshPostgres.DataLayer
    # authorizers: [Ash.Policy.Authorizer]

  alias Observer.Graph.Node.FamilyTreeManager

  postgres do
    table "graph_nodes"
    repo Observer.Repo
  end

  # policies do
  #   policy action_type([:read, :update, :destroy]) do
  #     authorize_if relates_to_actor_via([:organization, :users])
  #   end
  # end

  multitenancy do
    strategy :attribute
    attribute :organization_id
  end

  relationships do
    belongs_to :organization, Observer.Access.Organization,
      allow_nil?: false

    belongs_to :parent, __MODULE__
    has_many :children, __MODULE__,
      source_attribute: :id,
      destination_attribute: :parent_id

    has_many :ancestors, __MODULE__,
      manual: Observer.Graph.Node.AncestorsRelationship

    has_many :descendants, __MODULE__,
      manual: Observer.Graph.Node.DescendantsRelationship

    many_to_many :source_nodes, Observer.Graph.Node,
      through: Observer.Graph.Link,
      source_attribute_on_join_resource: :source_id,
      destination_attribute_on_join_resource: :target_id

    many_to_many :target_nodes, Observer.Graph.Node,
      through: Observer.Graph.Link,
      source_attribute_on_join_resource: :target_id,
      destination_attribute_on_join_resource: :source_id
  end

  attributes do
    uuid_v7_primary_key :id
    attribute :title, :string, allow_nil?: false, public?: true
    attribute :ancestor_ids, {:array, :uuid}, allow_nil?: false, default: []
    attribute :descendant_ids, {:array, :uuid}, allow_nil?: false, default: []

    timestamps()
  end

  actions do
    defaults [:read, :destroy, create: [:title, :parent_id], update: [:title, :parent_id]]

    update :recalculate_relationships do
      change atomic_update(:ancestor_ids, {:atomic, expr(ancestors.id)})
      # change atomic_update(:descendant_ids, {:atomic, expr(descendants.id)})
    end
  end

  # changes do
  #   change after_action(&FamilyTreeManager.on_parent_change/3), where: changing(:parent_id)
  # end
end
```
```elixir
defmodule Observer.Graph.Node.AncestorsRelationship do
  use Ash.Resource.ManualRelationship
  use AshPostgres.ManualRelationship
  alias Observer.Graph.Node
  alias Observer.Repo
  import Ecto.Query

  @doc false
  @impl true
  @spec load([Node.t()], keyword, map) ::
          {:ok, %{Ash.UUID.t() => [Node.t()]}} | {:error, any}
  def load(nodes, opts, context) do
    parent_ids = Enum.map(nodes, & &1.parent_id)

    ancestors =
      Node
      |> where([node], node.id in ^parent_ids)
      |> recursive_cte_query("node_tree", Node)
      |> Repo.all()

    nodes
    |> with_ancestors(ancestors)
    |> Map.new(&{&1.id, &1.ancestors})
    |> then(&{:ok, &1})
  end

  defp with_ancestors(nodes, ancestors) do
    Enum.map(nodes, fn node ->
      %{node | ancestors: get_ancestors(node, ancestors)}
    end)
  end

  defp get_ancestors(node, ancestors) do
    case Enum.find(ancestors, & &1.id === node.parent_id) do
      nil -> []
      found -> [found | get_ancestors(found, ancestors)]
    end
  end

  @doc false
  @impl true
  @spec ash_postgres_join(
          Ecto.Query.t(),
          opts :: keyword,
          current_binding :: any,
          as_binding :: any,
          :inner | :left,
          Ecto.Query.t()
        ) ::
          {:ok, Ecto.Query.t()} | {:error, any}
  # Add a join from some binding in the query, producing *as_binding*.
  def ash_postgres_join(query, _opts, current_binding, as_binding, join_type, destination_query) do
    immediate_parents =
      from(destination in destination_query,
        where: parent_as(^current_binding).id == destination.parent_id
      )

    cte_name = "nodes_#{as_binding}"

    descendant_query =
      recursive_cte_query_for_join(
        immediate_parents,
        cte_name,
        destination_query
      )

    case join_type do
      :inner ->
        {:ok,
         from(row in query,
           inner_lateral_join: descendant in subquery(descendant_query),
           on: true,
           as: ^as_binding
         )}

      :left ->
        {:ok,
         from(row in query,
           left_lateral_join: descendant in subquery(descendant_query),
           on: true,
           as: ^as_binding
         )}
    end
  end

  @impl true
  @spec ash_postgres_subquery(keyword, any, any, Ecto.Query.t()) ::
          {:ok, Ecto.Query.t()} | {:error, any}
  # Produce a subquery using which will use the given binding and will be
  def ash_postgres_subquery(_opts, current_binding, as_binding, destination_query) do
    immediate_ancestors =
      from(destination in Node,
        where: parent_as(^current_binding).parent_id == destination.id
      )

    cte_name = "nodes_#{as_binding}"

    recursive_cte_query =
      recursive_cte_query_for_join(
        immediate_ancestors,
        cte_name,
        Node
      )

    other_query =
      from(row in subquery(recursive_cte_query),
        where:
          row.id in subquery(
            from(row in Ecto.Query.exclude(destination_query, :select), select: row.id)
          )
      )

    {:ok, other_query}
  end

  defp recursive_cte_query(immediate_parents, cte_name, query) do
    recursion_query =
      query
      |> join(:inner, [parent], child in ^cte_name, on: parent.id == child.parent_id)

    ancestors_query =
      immediate_parents
      |> union(^recursion_query)

    {cte_name, Node}
    |> recursive_ctes(true)
    |> with_cte(^cte_name, as: ^ancestors_query)
  end

  defp recursive_cte_query_for_join(immediate_parents, cte_name, query) do
    # This is due to limitations in ecto's recursive CTE implementation
    # For more, see here:
    # https://elixirforum.com/t/ecto-cte-queries-without-a-prefix/33148/2
    # https://stackoverflow.com/questions/39458572/ecto-declare-schema-for-a-query
    node_keys = Node.__schema__(:fields)

    cte_name =
      from(cte in fragment("?", literal(^cte_name)), select: map(cte, ^node_keys))

    recursion_query =
      query
      |> join(:inner, [parent], child in ^cte_name, on: parent.id == child.parent_id)

    ancestors_query =
      immediate_parents
      |> union(^recursion_query)

    cte_name
    |> recursive_ctes(true)
    |> with_cte(^cte_name, as: ^ancestors_query)
  end
end
```

I think this is all code. If something missing let me know.

**Comment by zachdaniel** [comment]
If at all possible, a reproduction project or a reproduction in tests would go a long way towards isolating this one.
