### ISSUE TITLE
Error not handled properly when using `nil_items?` on embedded resource

### ISSUE THREAD

**Issue by michaelst** [ash-project/ash#274]
```
calculate :spent_by_month, {:array, SpentByMonth}, Spendable.User.Calculations.SpentByMonth do
  allow_nil? false
  constraints [nil_items?: false]
end
```

```
== Compilation error in file lib/spendable/resources/user.ex ==
** (FunctionClauseError) no function clause matching in Enumerable.List.reduce/3    
    
    The following arguments were given to Enumerable.List.reduce/3:
    
        # 1
        []
    
        # 2
        {:error, %NimbleOptions.ValidationError{key: [:nil_items?], keys_path: [], message: "unknown options [:nil_items?], valid options are: [:sort, :load, :create_action, :update_action, :destroy_action, :__source__]", value: nil}}
    
        # 3
        #Function<2.79411643/2 in Ash.Resource.Transformers.SetTypes.set_calculation_types/1>
    
    Attempted function clauses (showing 4 out of 4):
    
        def reduce(_list, {:halt, acc}, _fun)
        def reduce(list, {:suspend, acc}, fun)
        def reduce([], {:cont, acc}, _fun)
        def reduce([head | tail], {:cont, acc}, fun)
    
    (elixir 1.12.2) lib/enum.ex:4277: Enumerable.List.reduce/3
    (elixir 1.12.2) lib/enum.ex:2431: Enum.reduce_while/3
    (ash 1.48.0-rc.10) lib/ash/dsl/extension.ex:503: anonymous fn/4 in Ash.Dsl.Extension.run_transformers/4
    (elixir 1.12.2) lib/enum.ex:4280: Enumerable.List.reduce/3
    (elixir 1.12.2) lib/enum.ex:2431: Enum.reduce_while/3
    (stdlib 3.15.1) erl_eval.erl:685: :erl_eval.do_apply/6
    (ash 1.48.0-rc.10) /Users/Michael/Code/spendable/backend/lib/spendable/resources/user.ex:1: Ash.Dsl.__before_compile__/1
    (elixir 1.12.2) lib/kernel/parallel_compiler.ex:319: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/7
** (exit) shutdown: 1
    (iex 1.12.2) lib/iex/helpers.ex:106: IEx.Helpers.recompile/1
```

**Comment by zachdaniel** [comment]
This is resolved in master
