### ISSUE TITLE
Flows: Transaction into nested branches gives Engine Deadlock! Error

### ISSUE THREAD

**Issue by tommasop** [ash-project/ash#463]
**Describe the bug**
When in a flow there is a `transaction` into nested `branch` the framework givves this error:

```
** (RuntimeError) Engine Deadlock! No async tasks and state is the same after iteration.
```

**To Reproduce**
```
defmodule MmsBiztalk.Flows.ImportInvoice do
  use Ash.Flow

  flow do
    api MmsBiztalk.Support

    argument :attrs, :map do
      allow_nil? false
    end

    returns :create_invoice
  end

  steps do
    custom :get_invoice, MmsBiztalk.Flow.Steps.GetInvoice do
      input %{payment_id: path(arg(:attrs), [:payment_id])}
    end

    branch :invoice_not_found, expr(not ^result(:get_invoice)) do
      custom :get_customer, MmsBiztalk.Steps.GetCustomer do
        input %{help_desk_id: path(arg(:attrs), [:help_desk_id])}
      end

      branch :customer_found, expr(^result(:get_customer)) do
        transaction :create_data_in_and_invoice, MmsBiztalk.Support.Invoice do
          create :create_data_in, MmsBiztalk.Support.DataIn, :create do
            input %{data_type: "invoice"}
          end

          custom :create_invoice, MmsBiztalk.Flow.Steps.CreateInvoice do
            input %{
              attrs: arg(:attrs),
              data_in: result(:create_data_in),
              customer: result(:get_customer)
            }
          end
        end
      end
    end
  end
end

**Expected behavior**
The flow should be executed without any error.

**Runtime**
 - Elixir version 1.14.2
 - Erlang version 25
 - OS Pop OS 22.04
 - Ash version 2.4.26

**Comment by tommasop** [comment]
Let me know if you also need the custom steps and/or the resources.

Thanks a lot

**Comment by zachdaniel** [comment]
Hey there! I believe I've fixed this in main, if you don't mind trying it out. I'll close this issue for now, but feel free to reopen :)

**Comment by tommasop** [comment]
I found another similar issue and thus I'm posting it here.
I'm using carbonite but from the tests it seems the problem is related to Ash.

```elixir
defmodule Flows.TestFlow do
  use Ash.Flow

  flow do
    api MmsBiztalk

    argument :do_branch, :boolean do
      allow_nil? false
    end

    argument :customer_id, :uuid do
      allow_nil? false
    end

    argument :esolver_id, :integer do
      allow_nil? false
    end

    returns :set_to_synced
  end

  steps do
    branch :customer_data_from_esolver, arg(:do_branch) do
      custom :get_customer, MmsBiztalk.Flows.Steps.GetCustomer do
        input %{id: arg(:customer_id)}
      end

      transaction :update_customer_with_esolver, MmsBiztalk.Customer do
        update :save_esolver_id, MmsBiztalk.Customer, :set_esolver_id do
          record result(:get_customer)
          input %{esolver_id: arg(:esolver_id)}
        end

        update :set_to_synced, MmsBiztalk.Customer, :is_synced do
          record result(:get_customer)
        end
      end
    end
  end
end
```
This are the tests:

```elixir
 describe "Test transaction behavior with carbonite" do
    setup :setup_data_in_and_customer

    test "customer is correctly updated", %{customer: customer} do
      assert customer.synced == false

      customer 
      |> Ash.Changeset.for_update(:is_synced)
      |> MmsBiztalk.update!()

      customer = MmsBiztalk.reload!(customer)
      assert customer.synced == true
    end

    test "customer is correctly updated multiple times", %{customer: customer} do
      assert customer.synced == false
      assert customer.esolver_id == nil

      customer 
      |> Ash.Changeset.for_update(:is_synced)
      |> MmsBiztalk.update!()

      customer 
      |> Ash.Changeset.for_update(:set_esolver_id, %{esolver_id: 1000})
      |> MmsBiztalk.update!()

      customer = MmsBiztalk.reload!(customer)
      assert customer.synced == true
      assert customer.esolver_id == 1000
    end

    test "flow with branch and transaction and carbonite", %{customer: customer} do
      assert customer.synced == false
      assert customer.esolver_id == nil
      Flows.TestFlow.run!(true, customer.id, 300)

      assert customer.synced == true
      assert customer.esolver_id == 300
    end

    test "flow with branch and transaction: disable carbonite", %{customer: customer} do
      # this disables carbonite tracking
      carbonite_override_mode("track")
      assert customer.synced == false
      assert customer.esolver_id == nil
      Flows.TestFlow.run!(true, customer.id, 300)

      assert customer.synced == true
      assert customer.esolver_id == 300
    end
  end
```
And these are the results for failing tests:

```elixir
 1) test Test transaction behavior with carbonite flow with branch and transaction: disable carbonite (Flows.EsolverCustomerManagerTest)
     test/flows/esolver_customer_manager_test.exs:119
     ** (RuntimeError) Engine Deadlock! No async tasks and state is the same after iteration.
     
     
     
     Requests:
     Fetch record for :save_esolver_id
        state: fetch_data
     
     prepare MmsBiztalk.Customer.set_esolver_id: MmsBiztalk.Customer.set_esolver_id
        state: fetch_data | depends on "Fetch record for :save_esolver_id".data
     
     commit MmsBiztalk.Customer.set_esolver_id: MmsBiztalk.Customer.set_esolver_id
        state: fetch_data | depends on "prepare MmsBiztalk.Customer.set_esolver_id".changeset
     
     Fetch record for :set_to_synced
        state: fetch_data
     
     prepare MmsBiztalk.Customer.is_synced: MmsBiztalk.Customer.is_synced
        state: fetch_data | depends on "Fetch record for :set_to_synced".data
     
     commit MmsBiztalk.Customer.is_synced: MmsBiztalk.Customer.is_synced
        state: fetch_data | depends on "prepare MmsBiztalk.Customer.is_synced".changeset
     
     
     
     stacktrace:
       (ash 2.5.2) lib/ash/engine/engine.ex:264: Ash.Engine.run_to_completion/1
       (ash 2.5.2) lib/ash/engine/engine.ex:202: Ash.Engine.do_run/2
       (ash 2.5.2) lib/ash/engine/engine.ex:102: anonymous fn/2 in Ash.Engine.run/2
       (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
       (ash 2.5.2) lib/ash/engine/engine.ex:99: Ash.Engine.run/2
       (ash 2.5.2) lib/ash/flow/executor/ash_engine.ex:423: anonymous fn/9 in Ash.Flow.Executor.AshEngine.requests/5
       (ash 2.5.2) lib/ash/engine/request.ex:1028: Ash.Engine.Request.do_try_resolve_local/4
       (ash 2.5.2) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
       (ash 2.5.2) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
       (ash 2.5.2) lib/ash/engine/engine.ex:650: Ash.Engine.advance_request/2
       (ash 2.5.2) lib/ash/engine/engine.ex:556: Ash.Engine.fully_advance_request/2
       (ash 2.5.2) lib/ash/engine/engine.ex:497: Ash.Engine.do_run_iteration/2
       (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash 2.5.2) lib/ash/engine/engine.ex:257: Ash.Engine.run_to_completion/1
       (ash 2.5.2) lib/ash/engine/engine.ex:202: Ash.Engine.do_run/2
       (ash 2.5.2) lib/ash/engine/engine.ex:141: Ash.Engine.run/2
       (ash 2.5.2) lib/ash/flow/executor/ash_engine.ex:161: Ash.Flow.Executor.AshEngine.execute/3
       (ash 2.5.2) lib/ash/flow/flow.ex:45: Ash.Flow.run/3
       (ash 2.5.2) lib/ash/flow/flow.ex:19: Ash.Flow.run!/3

  * test Test transaction behavior with carbonite flow with branch and transaction and carbonite (12.9ms) [L#110]

  2) test Test transaction behavior with carbonite flow with branch and transaction and carbonite (Flows.EsolverCustomerManagerTest)
     test/flows/esolver_customer_manager_test.exs:110
     ** (RuntimeError) Engine Deadlock! No async tasks and state is the same after iteration.
     
     
     
     Requests:
     Fetch record for :save_esolver_id
        state: fetch_data
     
     prepare MmsBiztalk.Customer.set_esolver_id: MmsBiztalk.Customer.set_esolver_id
        state: fetch_data | depends on "Fetch record for :save_esolver_id".data
     
     commit MmsBiztalk.Customer.set_esolver_id: MmsBiztalk.Customer.set_esolver_id
        state: fetch_data | depends on "prepare MmsBiztalk.Customer.set_esolver_id".changeset
     
     Fetch record for :set_to_synced
        state: fetch_data
     
     prepare MmsBiztalk.Customer.is_synced: MmsBiztalk.Customer.is_synced
        state: fetch_data | depends on "Fetch record for :set_to_synced".data
     
     commit MmsBiztalk.Customer.is_synced: MmsBiztalk.Customer.is_synced
        state: fetch_data | depends on "prepare MmsBiztalk.Customer.is_synced".changeset
     
     
     
     stacktrace:
       (ash 2.5.2) lib/ash/engine/engine.ex:264: Ash.Engine.run_to_completion/1
       (ash 2.5.2) lib/ash/engine/engine.ex:202: Ash.Engine.do_run/2
       (ash 2.5.2) lib/ash/engine/engine.ex:102: anonymous fn/2 in Ash.Engine.run/2
       (ecto_sql 3.9.2) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.4.3) lib/db_connection.ex:1611: DBConnection.run_transaction/4
       (ash 2.5.2) lib/ash/engine/engine.ex:99: Ash.Engine.run/2
       (ash 2.5.2) lib/ash/flow/executor/ash_engine.ex:423: anonymous fn/9 in Ash.Flow.Executor.AshEngine.requests/5
       (ash 2.5.2) lib/ash/engine/request.ex:1028: Ash.Engine.Request.do_try_resolve_local/4
       (ash 2.5.2) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
       (ash 2.5.2) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
       (ash 2.5.2) lib/ash/engine/engine.ex:650: Ash.Engine.advance_request/2
       (ash 2.5.2) lib/ash/engine/engine.ex:556: Ash.Engine.fully_advance_request/2
       (ash 2.5.2) lib/ash/engine/engine.ex:497: Ash.Engine.do_run_iteration/2
       (elixir 1.14.1) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash 2.5.2) lib/ash/engine/engine.ex:257: Ash.Engine.run_to_completion/1
       (ash 2.5.2) lib/ash/engine/engine.ex:202: Ash.Engine.do_run/2
       (ash 2.5.2) lib/ash/engine/engine.ex:141: Ash.Engine.run/2
       (ash 2.5.2) lib/ash/flow/executor/ash_engine.ex:161: Ash.Flow.Executor.AshEngine.execute/3
       (ash 2.5.2) lib/ash/flow/flow.ex:45: Ash.Flow.run/3
       (ash 2.5.2) lib/ash/flow/flow.ex:19: Ash.Flow.run!/3


Finished in 0.6 seconds (0.00s async, 0.6s sync)
```

**Comment by zachdaniel** [comment]
Something strange is definitely going on here. Could you confirm that your initial custom step returns successfully?

**Comment by tommasop** [comment]
Yes I confirm that the first two tests pass flawlessly.

**Comment by zachdaniel** [comment]
This was resolved, forgot to close the issue. Should have linked the commit, but it was too long ago and I can't be assed to go hunt it down.
