### ISSUE TITLE
Generator of :decimal with constraints is broken

### ISSUE THREAD

**Issue by oco-adam** [ash-project/ash#467]
**Describe the bug**
Generated values of resource attributes of :decimal type with a :min constraint don't work

**To Reproduce**
make a resource with the following attribute
```elixir
attribute :decimal_with_constraints, :decimal do
        constraints min: 1.0
end
```
Then run the following test a few times:
```
test "action input can be provided to an action" do
    check all(input <- Ash.Generator.action_input(MyResource, :create)) do
      MyResource
      |> Ash.Changeset.for_create(:create, input)
      |> MyApi.create!()
    end
  end
  ```
  It will fail with an error of the following form:
  ```
   ** (ArithmeticError) bad argument in arithmetic expression: 2.0 + #Decimal<1.0>
     stacktrace:
       :erlang.+(2.0, #Decimal<1.0>)
       (stream_data 0.5.0) lib/stream_data.ex:1545: anonymous fn/2 in StreamData.float/1
       (stream_data 0.5.0) lib/stream_data/lazy_tree.ex:36: StreamData.LazyTree.map/2
       (stream_data 0.5.0) lib/stream_data.ex:202: anonymous fn/4 in StreamData.map/2
       (stream_data 0.5.0) lib/stream_data.ex:202: anonymous fn/3 in StreamData.bind_filter/5
       (stream_data 0.5.0) lib/stream_data/lazy_tree.ex:36: StreamData.LazyTree.map/2
       (stream_data 0.5.0) lib/stream_data.ex:384: StreamData.bind_filter/5
       (stream_data 0.5.0) lib/stream_data.ex:351: anonymous fn/5 in StreamData.bind_filter/3
       (stream_data 0.5.0) lib/stream_data.ex:202: StreamData.call/3
       (stream_data 0.5.0) lib/stream_data.ex:219: anonymous fn/4 in StreamData.fixed_list/1
       (elixir 1.14.0) lib/enum.ex:1786: anonymous fn/3 in Enum.map_reduce/3
       (elixir 1.14.0) lib/enum.ex:4299: Enum.reduce_range/5
       (elixir 1.14.0) lib/enum.ex:2472: Enum.map_reduce/3
       (stream_data 0.5.0) lib/stream_data.ex:216: anonymous fn/3 in StreamData.fixed_list/1
       (elixir 1.14.0) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
       (stream_data 0.5.0) lib/stream_data.ex:1154: anonymous fn/3 in StreamData.fixed_list/1
       (stream_data 0.5.0) lib/stream_data.ex:202: StreamData.call/3
       (stream_data 0.5.0) lib/stream_data.ex:282: anonymous fn/3 in StreamData.fixed_map/1
       (stream_data 0.5.0) lib/stream_data.ex:202: anonymous fn/4 in StreamData.optional_map/1
       (stream_data 0.5.0) lib/stream_data.ex:202: StreamData.call/3
  ```

**Expected behavior**
The test doesn't fail

**Runtime**
 - Elixir version
 1.14.0
 - Erlang version
 Erlang/OTP 25
 - OS
 macOS
 - Ash version
 Main
 - any related extension versions

**Additional context**
https://discord.com/channels/711271361523351632/955933117573652563/1054793900046426192

**Comment by zachdaniel** [comment]
This should be addressed in main.
