### ISSUE TITLE
Recursive Flow leads to infinte loop

### ISSUE THREAD

**Issue by barnabasJ** [ash-project/ash#503]
**Describe the bug**

Running an recursive flow leads to infinite recursion

**To Reproduce**
```elixir
 run_flow :next, __MODULE__ do
```

**Expected behavior**
Flow should run and stop as long as there is a `base case`

**Runtime**
 - Elixir version 14.3
 - Erlang version 25.2
 - OS Ubuntu 22.04
 - Ash version commit: 54f3a4732600423a6b6108c5de6fc14e7f3373da
 - any related extension versions

**Additional context**

**Comment by barnabasJ** [comment]
I tried creating a test. But while coming up with an example flow I got this error a couple times. I can't spend any more time on this today, but can try to create a test in the coming days. 

```
  1) test run flow (Demo.FlowTest)
     test/demo/flow_test.exs:55
     ** (CaseClauseError) no case clause matching: true
     code: Demo.FlowTest.Flow.run(4)
     stacktrace:
       (ash 2.5.16) lib/ash/engine/request.ex:1049: Ash.Engine.Request.do_try_resolve_local/4
       (ash 2.5.16) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
       (ash 2.5.16) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
       (ash 2.5.16) lib/ash/engine/engine.ex:650: Ash.Engine.advance_request/2
       (ash 2.5.16) lib/ash/engine/engine.ex:556: Ash.Engine.fully_advance_request/2
       (ash 2.5.16) lib/ash/engine/engine.ex:497: Ash.Engine.do_run_iteration/2
       (elixir 1.14.3) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash 2.5.16) lib/ash/engine/engine.ex:257: Ash.Engine.run_to_completion/1
       (ash 2.5.16) lib/ash/engine/engine.ex:202: Ash.Engine.do_run/2
       (ash 2.5.16) lib/ash/engine/engine.ex:141: Ash.Engine.run/2
       (ash 2.5.16) lib/ash/flow/executor/ash_engine.ex:161: Ash.Flow.Executor.AshEngine.execute/3
       (ash 2.5.16) lib/ash/flow/flow.ex:45: Ash.Flow.run/3
       test/demo/flow_test.exs:56: (test)
       ```
       
       ```elixir
defmodule Demo.FlowTest do
  use ExUnit.Case

  defmodule Demo.FlowTest.Flow do
    @moduledoc """

    """
    use Ash.Flow

    flow do
      api(Demo.Support)

      argument :n, :integer do
        allow_nil? false
        constraints min: 0
      end

      returns(:result)
    end

    steps do
      custom :is_not_base_case?, fn %{n: n}, _ -> n > 0 end do
        input(%{n: arg(:n)})
      end

      branch :calculate, result(:is_not_base_case?) do
        output :next

        custom :next_n, fn %{n: n}, _ ->
          IO.inspect(n)
          n - 1
        end do
          input %{
            n: arg(:n)
          }
        end

        run_flow :next, __MODULE__ do
          input %{
            n: result(:next_n)
          }
        end
      end

      custom :result, fn args, _ ->
        IO.inspect(args)
      end do
        input %{n: arg(:n), calculate: result(:calculate)}
      end
    end
  end

  test "run flow" do
    Demo.FlowTest.Flow.run(4)
    |> IO.inspect()
  end
end
 ```

**Comment by zachdaniel** [comment]
I'm going to close this because we will be changing flow to be backed by our new tool "Reactor". Reactor does not have this bug.
