### ISSUE TITLE
get_and_lock unhandled error

### ISSUE THREAD

**Issue by infinitis** [ash-project/ash#579]
Added the builtin change get_and_lock("FOR UPDATE NOWAIT") to an update action and when attempting to test out the functionality ran into an unhandled error.

**To Reproduce**
Manually begin a transaction in postgres with the target record and then attempt to run an action through an ash graphql endpoint.

**Expected behavior**
An error would be added to the changeset denoting the lock failed to be acquired.

**Runtime**
 - Elixir version: 1.14.2-otp-25
 - Erlang version: 25.2
 - OS: linux
 - Ash version: c99c36d8c8c591cd7d68eb5513e945155d75c6cb
 - ash_postgres: ec61c3f000b5092815e56a0052996783b318b5a5

Stacktrace:

```
14:22:29.441 function=log_exception/2 module=AshGraphql.Graphql.Resolver user_id=e8d058a2-d40b-46d4-bd87-0159be9d04f1 [error] c8f2f6fe-98ef-4d98-87ab-f63606183376: Exception raised while resolving query.

** (Ash.Error.Unknown) Context: resolving data on commit _______________________________

Unknown Error

Context: resolving data on fetch __________________
* Context: resolving data on fetch _____________________

** (Postgrex.Error) ERROR 55P03 (lock_not_available) could not obtain lock on row in relation "___________"
  (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
  (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
  (ecto 3.10.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
  (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
  (ash_postgres 1.3.25) lib/data_layer.ex:628: AshPostgres.DataLayer.run_query/2
  (ash 2.9.6) lib/ash/actions/read.ex:2292: Ash.Actions.Read.run_query/6
  (ash 2.9.6) lib/ash/actions/read.ex:1102: anonymous fn/4 in Ash.Actions.Read.data_field/3
  (ash 2.9.6) lib/ash/engine/request.ex:1048: Ash.Engine.Request.do_try_resolve_local/4
  (ash 2.9.6) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
  (ash 2.9.6) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
  (ash 2.9.6) lib/ash/engine/engine.ex:712: Ash.Engine.advance_request/2
  (ash 2.9.6) lib/ash/engine/engine.ex:637: Ash.Engine.fully_advance_request/2
  (ash 2.9.6) lib/ash/engine/engine.ex:578: Ash.Engine.do_run_iteration/2
  (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 2.9.6) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
  (ash 2.9.6) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
  (ash 2.9.6) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
  (ash 2.9.6) lib/ash/actions/read.ex:173: Ash.Actions.Read.do_run/3
  (ash 2.9.6) lib/ash/actions/read.ex:96: Ash.Actions.Read.run/3
  (ash 2.9.6) lib/ash/api/api.ex:1454: Ash.Api.get/4
  (_________ 2.0.0) lib/_________/resources/api.ex:1: __________.API.get/3
  (ash 2.9.6) lib/ash/resource/change/get_and_lock.ex:12: anonymous fn/3 in Ash.Resource.Change.GetAndLock.change/3
  (ash 2.9.6) lib/ash/changeset/changeset.ex:1907: anonymous fn/2 in Ash.Changeset.run_before_actions/1
  (elixir 1.14.2) lib/enum.ex:4751: Enumerable.List.reduce/3
  (elixir 1.14.2) lib/enum.ex:2514: Enum.reduce_while/3
  (ash 2.9.6) lib/ash/changeset/changeset.ex:1992: Ash.Changeset.run_around_actions/2
  (ash 2.9.6) lib/ash/changeset/changeset.ex:1664: anonymous fn/2 in Ash.Changeset.with_hooks/3
  (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:1203: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
  (db_connection 2.5.0) lib/db_connection.ex:1630: DBConnection.run_transaction/4
  (ash 2.9.6) lib/ash/changeset/changeset.ex:1662: anonymous fn/3 in Ash.Changeset.with_hooks/3
  (ash 2.9.6) lib/ash/changeset/changeset.ex:1774: Ash.Changeset.transaction_hooks/2
  (ash 2.9.6) lib/ash/changeset/changeset.ex:1644: Ash.Changeset.with_hooks/3
  (ash 2.9.6) lib/ash/actions/update.ex:353: anonymous fn/9 in Ash.Actions.Update.as_requests/5
  (ash 2.9.6) lib/ash/engine/request.ex:1048: Ash.Engine.Request.do_try_resolve_local/4
  (ash 2.9.6) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
  (ash 2.9.6) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
  (ash 2.9.6) lib/ash/engine/engine.ex:712: Ash.Engine.advance_request/2
  (ash 2.9.6) lib/ash/engine/engine.ex:637: Ash.Engine.fully_advance_request/2
  (ash 2.9.6) lib/ash/engine/engine.ex:578: Ash.Engine.do_run_iteration/2
  (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
  (ash 2.9.6) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
  (ash 2.9.6) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
  (ash 2.9.6) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
  (ash 2.9.6) lib/ash/actions/update.ex:82: Ash.Actions.Update.do_run/4
  (ash 2.9.6) lib/ash/actions/update.ex:38: Ash.Actions.Update.run/4
  (_______ 2.0.0) lib/________/resources/api.ex:1: ______________.API.update/2
  (ash_graphql 0.24.0) lib/graphql/resolver.ex:905: AshGraphql.Graphql.Resolver.mutate/2
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:232: Absinthe.Phase.Document.Execution.Resolution.reduce_resolution/1
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:187: Absinthe.Phase.Document.Execution.Resolution.do_resolve_field/3
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:172: Absinthe.Phase.Document.Execution.Resolution.do_resolve_fields/6
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:143: Absinthe.Phase.Document.Execution.Resolution.resolve_fields/4
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:88: Absinthe.Phase.Document.Execution.Resolution.walk_result/5
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:67: Absinthe.Phase.Document.Execution.Resolution.perform_resolution/3
  (absinthe 1.7.1) lib/absinthe/phase/document/execution/resolution.ex:24: Absinthe.Phase.Document.Execution.Resolution.resolve_current/3
  (absinthe 1.7.1) lib/absinthe/pipeline.ex:405: Absinthe.Pipeline.run_phase/3
  (absinthe_plug 1.5.8) lib/absinthe/plug.ex:536: Absinthe.Plug.run_query/4
  (absinthe_plug 1.5.8) lib/absinthe/plug.ex:290: Absinthe.Plug.call/2
  (phoenix 1.7.2) lib/phoenix/router/route.ex:42: Phoenix.Router.Route.call/2
  (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5
  (________ 2.0.0) lib/__________web/endpoint.ex:1: _________.Endpoint.plug_builder_call/2
  (________ 2.0.0) lib/plug/debugger.ex:136: ___________.Endpoint."call (overridable 3)"/2
  (________ 2.0.0) lib/___________web/endpoint.ex:1: ___________.Endpoint."call (overridable 4)"/2
  (________ 2.0.0) lib/spandex_phoenix.ex:151: _____________.Endpoint.call/2
  (phoenix 1.7.2) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:913: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.10.1) lib/ecto/adapters/sql.ex:828: Ecto.Adapters.SQL.execute/6
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ash_postgres 1.3.25) lib/data_layer.ex:628: AshPostgres.DataLayer.run_query/2
    (ash 2.9.6) lib/ash/actions/read.ex:2292: Ash.Actions.Read.run_query/6
    (ash 2.9.6) lib/ash/actions/read.ex:1102: anonymous fn/4 in Ash.Actions.Read.data_field/3
    (ash 2.9.6) lib/ash/engine/request.ex:1048: Ash.Engine.Request.do_try_resolve_local/4
    (ash 2.9.6) lib/ash/engine/request.ex:282: Ash.Engine.Request.do_next/1
    (ash 2.9.6) lib/ash/engine/request.ex:211: Ash.Engine.Request.next/1
    (ash 2.9.6) lib/ash/engine/engine.ex:712: Ash.Engine.advance_request/2
    (ash 2.9.6) lib/ash/engine/engine.ex:637: Ash.Engine.fully_advance_request/2
    (ash 2.9.6) lib/ash/engine/engine.ex:578: Ash.Engine.do_run_iteration/2
    (elixir 1.14.2) lib/enum.ex:2468: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ash 2.9.6) lib/ash/engine/engine.ex:307: Ash.Engine.run_to_completion/1
    (ash 2.9.6) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
    (ash 2.9.6) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
    (ash 2.9.6) lib/ash/actions/read.ex:173: Ash.Actions.Read.do_run/3
    (ash 2.9.6) lib/ash/actions/read.ex:96: Ash.Actions.Read.run/3
    (ash 2.9.6) lib/ash/api/api.ex:1454: Ash.Api.get/4
    (_______ 2.0.0) lib/________/resources/api.ex:1: _______.API.get/3
    (ash 2.9.6) lib/ash/resource/change/get_and_lock.ex:12: anonymous fn/3 in Ash.Resource.Change.GetAndLock.change/3
    (ash 2.9.6) lib/ash/changeset/changeset.ex:1907: anonymous fn/2 in Ash.Changeset.run_before_actions/1
    (elixir 1.14.2) lib/enum.ex:4751: Enumerable.List.reduce/3
    (elixir 1.14.2) lib/enum.ex:2514: Enum.reduce_while/3
    (ash 2.9.6) lib/ash/changeset/changeset.ex:1992: Ash.Changeset.run_around_actions/2
    (ash 2.9.6) lib/ash/changeset/changeset.ex:1664: anonymous fn/2 in Ash.Changeset.with_hooks/3
 (truncated)
```

**Comment by zachdaniel** [comment]
The first and most important step of this has been handled, specifically we now wrap raised errors on locks with an `Ash.Error.Invalid.Unavailable` error. TO have this show up nicely in `ash_graphql` we will need to implement the `AshGraphql.Error` protocol for it. I'll leave that for another day/let someone else PR it when they get to that point. It can also be implemented in individual applications. See the relevant error handling guide for more.
