### ISSUE TITLE
Defining an aggregate that returns a resource generates an Ecto error

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#580]
**Describe the bug**

I had the case where I wanted to define an aggregate that returned a full resource instance, not a field on a resource, eg.

* Instance has_one :most_recent_instance_log
* Project has_many :instances
* Project has an aggregate for the most recent instance log across all of the instances

I imagined this aggregate definition to look like:

```elixir
aggregates do
  first :most_recent_instance_log, :instances, :most_recent_instance_log
end
```

But this gave me a big Ecto error:

```
iex(5)>  MyApp.Project.by_id("43d74c6a-23a1-4959-8070-a5591613f88b", load: [:most_recent_instance_log])
** (Ecto.SubQueryError) the following exception happened when compiling a subquery.

    ** (UndefinedFunctionError) function :has_one.type/0 is undefined (module :has_one is not available)

The subquery originated from the following query:

from p0 in MyApp.Project,
  as: 0,
  left_lateral_join: i1 in subquery(from i0 in MyApp.Instance,
  as: 0,
  where: is_nil(type(as(0).archived_at, {:parameterized, Ash.Type.UtcDatetimeUsec.EctoType, []})) == ^true,
  where: is_nil(type(as(0).archived_at, {:parameterized, Ash.Type.UtcDatetimeUsec.EctoType, []})) == ^true,
  where: parent_as(0).id == as(0).project_id,
  group_by: [i0.project_id],
  select: merge(
  %{
    most_recent_instance_log:
      type(
        coalesce(
          fragment("array_agg(?)", ^most_recent_instance_log),
          type(^[], {:array, :has_one})
        ),
        {:array, :has_one}
      )
  },
  map(i0, [:project_id])
)),
  as: 1,
  on: true,
  where: is_nil(type(as(0).archived_at, {:parameterized, Ash.Type.UtcDatetimeUsec.EctoType, []})) == ^true,
  where: type(as(0).id, {:parameterized, Ash.Type.UUID.EctoType, []}) ==
  type(^"43d74c6a-23a1-4959-8070-a5591613f88b", {:parameterized, Ash.Type.UUID.EctoType, []}),
  select: merge(
  struct(p0, [
    :archived_at,
    :id,
    :project_id,
    :api_enabled,
    :display_name,
    :inserted_at,
    :updated_at,
    :vendor_id
  ]),
  %{
    most_recent_instance_log:
      type(
        coalesce(
          type(as(1).most_recent_instance_log, {:array, :has_one}),
          type(^[], {:array, :has_one})
        ),
        {:array, :has_one}
      )
  }
)

    (ecto 3.10.1) lib/ecto/repo/queryable.ex:211: Ecto.Repo.Queryable.execute/4
    (ecto 3.10.1) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
    (ash_postgres 1.3.25) lib/data_layer.ex:616: AshPostgres.DataLayer.run_query/2
    (ash 2.9.5) lib/ash/actions/read.ex:2292: Ash.Actions.Read.run_query/6
    (ash 2.9.5) lib/ash/actions/read.ex:1102: anonymous fn/4 in Ash.Actions.Read.data_field/3
    (ash 2.9.5) lib/ash/engine/engine.ex:537: anonymous fn/2 in Ash.Engine.run_iteration/1
    (ash 2.9.5) lib/ash/engine/engine.ex:558: anonymous fn/4 in Ash.Engine.async/2
    (elixir 1.14.3) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
    (elixir 1.14.3) lib/task/supervised.ex:34: Task.Supervised.reply/4
    (stdlib 4.3.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
    (ash 2.9.5) lib/ash/engine/engine.ex:552: Ash.Engine.async/2
    (elixir 1.14.3) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ash 2.9.5) lib/ash/engine/engine.ex:702: Ash.Engine.start_pending_tasks/1
    (ash 2.9.5) lib/ash/engine/engine.ex:323: Ash.Engine.run_to_completion/1
    (ash 2.9.5) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
    (ash 2.9.5) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
    (ash 2.9.5) lib/ash/actions/read.ex:173: Ash.Actions.Read.do_run/3
    (ash 2.9.5) lib/ash/actions/read.ex:96: Ash.Actions.Read.run/3
    (ash 2.9.5) lib/ash/api/api.ex:1790: Ash.Api.read_one/3
    iex:5: (file)
```

As you mentioned to me, this isn't actually supported functionality (and probably never will be) but this error isn't great to know what's going on or why.

**Expected behavior**

A more useful error message, letting me know that actually this isn't supported behaviour, you can't return a resource as part of an aggregate, only a field of a resource. 

**Runtime**

 - Elixir version 1.14.3
 - Erlang version 25.0.4
 - Ash version 2.9.5

**Comment by zachdaniel** [comment]
So what needs to happen here is that we need to add a registry level validation of aggregate paths, to ensure that the field at the end of the path is an attribute or calculation.

**Comment by franckstifler** [comment]
WIP.
