### ISSUE TITLE
Aggregates loaded in the action is not available for publishing

### ISSUE THREAD

**Issue by puruzio** [ash-project/ash#621]
**Describe the bug**
aggregates loaded via `change load[:aggregate_field]` is showing up as nil when `publish :create, ["update_signup", :aggregate_field]` runs.

**To Reproduce**
A minimal set of resource definitions and calls that can reproduce the bug.
See above description

**Expected behavior**

**Runtime**
 - Elixir version  1.14.1
 - Erlang version   25
 - OS    Windows 11
 - Ash version    2.9.25
 - any related extension versions  Ash postgres 1.3.30

**Additional context**

Error message:
````
commit []
Γå│ anonymous fn/3 in Ash.Changeset.with_hooks/3, at: lib/ash/changeset/changeset.ex:1733
[debug] QUERY OK source="signups" db=18.1ms queue=0.1ms idle=1655.6ms
SELECT s0."id", i1."aggregate_field1" FROM "signups" AS s0 LEFT OUTER JOIN "public"."items" AS i1 ON s0."item_id" = i1."id" WHERE (s0."id"::uuid = $1::uuid) ["33b1d69d-14a8-413c-83c2-613961d43c5b"]
Γå│ AshPostgres.DataLayer.run_query/2, at: lib/data_layer.ex:628
** (Protocol.UndefinedError) protocol String.Chars not implemented for #Ash.NotLoaded<:aggregate> of type Ash.NotLoaded (a struct). This protocol is implemented for the following type(s): Ash.CiString, Ato..
    (elixir 1.14.1) lib/string/chars.ex:3: String.Chars.impl_for!/1
    (elixir 1.14.1) lib/string/chars.ex:22: String.Chars.to_string/1
    (elixir 1.14.1) lib/enum.ex:3991: Enum.join_non_empty_list/3
    (elixir 1.14.1) lib/enum.ex:4272: Enum.join_list/2
    (elixir 1.14.1) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (ash 2.9.25) lib/ash/notifier/pub_sub/pub_sub.ex:216: Ash.Notifier.PubSub.fill_template/2
    (ash 2.9.25) lib/ash/notifier/pub_sub/pub_sub.ex:143: Ash.Notifier.PubSub.publish_notification/2
    (elixir 1.14.1) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by zachdaniel** [comment]
fixed in main.
