### ISSUE TITLE
Regression in bulk_create from v2.14.20 to v2.14.21

### ISSUE THREAD

**Issue by sevenseacat** [ash-project/ash#706]
**Describe the bug**

A Dependabot PR in our app has flagged a possible regression in the behaviour of `bulk_create` - 

```
     ** (BadMapError) expected a map, got: nil
     code: assert {:ok, []} = perform_job(SyncProjects, %{})
     stacktrace:
       (elixir 1.15.5) lib/map.ex:535: Map.get(nil, :context, nil)
       (ash 2.14.21) lib/ash/actions/create/bulk.ex:163: anonymous fn/7 in Ash.Actions.Create.Bulk.do_run/5
       (elixir 1.15.5) lib/stream.ex:613: anonymous fn/4 in Stream.map/2
       (elixir 1.15.5) lib/enum.ex:4830: Enumerable.List.reduce/3
       (elixir 1.15.5) lib/stream.ex:1027: Stream.do_transform_inner_list/7
       (elixir 1.15.5) lib/stream.ex:1828: Enumerable.Stream.do_each/4
       (elixir 1.15.5) lib/enum.ex:4387: Enum.reduce/3
       (ash 2.14.21) lib/ash/actions/create/bulk.ex:399: Ash.Actions.Create.Bulk.do_run/5
       (ash 2.14.21) lib/ash/actions/create/bulk.ex:70: Ash.Actions.Create.Bulk.run/5
       (my_app 0.96.2) lib/my_app/cloud.ex:1: MyApp.Cloud.bulk_create/4
       (my_app 0.96.2) lib/my_app/workers/sync_projects.ex:57: MyApp.Worker.SyncProjects.sync_projects/1
```

Line 57 of `sync_projects/1` - 

```elixir
    list
    |> Cloud.bulk_create(Cloud.Project, :upsert,
      authorize?: false,
      return_records?: true,
      return_errors?: true,
      notify?: true
    )
```

**Runtime**
 - Elixir version 1.15.5
 - Erlang version 26.0.2
 - OS macOS
 - Ash version 2.14.21

**Comment by zachdaniel** [comment]
Fixed in d07ca08
