### ISSUE TITLE
Typo in datalayer produces somewhat cryptic error messages (and compile deadlocks if using extensions)

### ISSUE THREAD

**Issue by olivermt** [ash-project/ash#791]
**Describe the bug**
```
== Compilation error in file lib/safari/virtual/resources/cesium_asset_file_copy.ex ==
** (ArgumentError) could not load module AshPostgres.Datalayer due to reason :nofile
    (elixir 1.15.6) lib/code.ex:1888: Code.ensure_compiled!/1
    (ash 2.15.6) lib/ash/data_layer/data_layer.ex:395: Ash.DataLayer.source/1
    /Users/olivermt/code/safari/app/lib/safari/virtual/resources/cesium_asset_file_copy.ex:1: (file)
    (stdlib 5.1.1) erl_eval.erl:750: :erl_eval.do_apply/7
    (stdlib 5.1.1) erl_eval.erl:494: :erl_eval.expr/6
    (stdlib 5.1.1) erl_eval.erl:136: :erl_eval.exprs/6
    (stdlib 5.1.1) erl_eval.erl:282: :erl_eval.expr/6
```

If you add an extension it just goes into deadlock and the compile never finishes, I only discovered the nofile thing when I removed the AshOban extension.

**To Reproduce**
Misspell datalayer like `data_layer: AshPostgres.Datalayer` (lower case l)

**Expected behavior**
Tell me that I am specifying a data layer that does not exist, :nofile sounds like it can be anything even though in **hindsight** it makes to be nofile due to my typo

**Runtime**
 - Ash version 2.15.6

**Comment by jimsynz** [comment]
I suspect that this is actually an issue in Spark that we need to have better validations of DSL extensions.

**Comment by Jsime34** [comment]
I dug into this issue and found out that this was an issue within AshDataLayer source and how it was handling Code.ensure_compiled!/1. You may be right about the Spark issue, but I did not go that way as this problem was happening during the schema building, before any verifiers run.

**Comment by zachdaniel** [comment]
👍 are you planning on putting together a fix @Jsime34 ?
