### ISSUE TITLE
protocol Enumerable not implemented Ash.Union struct

### ISSUE THREAD

**Issue by rgraff** [ash-project/ash#802]
**Describe the bug**

Casting a liists of unions raises an Protocol.UndefinedError. Introduced sometime between 2.17.7 and 2.17.9.

```elixir
** (Protocol.UndefinedError) protocol Enumerable not implemented for %{__index__: 1, __struct__: Ash.Union, type: :string, value: #Kickplan.Environments.FeatureVariant.String<__meta__: #Ecto.Schema.Metadata<:built, "">, id: "c1addfa7-80d6-4d8a-b1a9-3fd676da346c", key: #Ash.CiString<"green">, value: "green", type: :string, description: "this is blue", maxtrix_description: nil, metadata: "{}", enabled: true, aggregates: %{}, calculations: %{}, ...>} of type Ash.Union (a struct).
(elixir 1.15.4) lib/enum.ex:1: Enumerable.impl_for!/1
       (elixir 1.15.4) lib/enum.ex:166: Enumerable.reduce/3
       (elixir 1.15.4) lib/enum.ex:1553: Enum.reduce_into_protocol/3
       (elixir 1.15.4) lib/enum.ex:1537: Enum.into_protocol/2
       (ash 2.17.10) lib/ash/changeset/changeset.ex:1168: Ash.Changeset.cast_params/3
       (ash 2.17.10) lib/ash/changeset/changeset.ex:934: Ash.Changeset.handle_params/4
       (ash 2.17.10) lib/ash/changeset/changeset.ex:886: Ash.Changeset.do_for_action/4
       (kickplan 0.1.0) deps/ash/lib/ash/embeddable_type.ex:156: Kickplan.Environments.FeatureVariant.String.cast_input/2
       (ash 2.17.10) lib/ash/type/type.ex:546: Ash.Type.cast_input/3
       (ash 2.17.10) lib/ash/type/union.ex:223: Ash.Type.Union.cast_input/2
       (ash 2.17.10) lib/ash/type/type.ex:546: Ash.Type.cast_input/3
       (ash 2.17.10) lib/ash/type/type.ex:1066: anonymous fn/3 in Ash.Type.Union.cast_input_array/2
       (elixir 1.15.4) lib/enum.ex:4830: Enumerable.List.reduce/3
       (elixir 1.15.4) lib/enum.ex:2564: Enum.reduce_while/3
       (ash 2.17.10) lib/ash/type/helpers.ex:10: Ash.Type.Helpers.cast_input/5
       (ash 2.17.10) lib/ash/changeset/changeset.ex:3477: Ash.Changeset.change_attribute/3
       (ash 2.17.10) lib/ash/changeset/changeset.ex:1261: anonymous fn/6 in Ash.Changeset.run_action_changes/6
       (elixir 1.15.4) lib/enum.ex:2510: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ash 2.17.10) lib/ash/changeset/changeset.ex:887: Ash.Changeset.do_for_action/4
       (kickplan 0.1.0) deps/ash/lib/ash/code_interface.ex:562: Kickplan.Environments.Feature.add_variant!/3
```

**Additional context**
Discussed in discord #main-liners

**Comment by zachdaniel** [comment]
@rgraff I'm having trouble tracking this down. I'm going to need a reproduction test, or some help tracking down where things might be going wrong.

**Comment by rgraff** [comment]
Fixed in main
