### ISSUE TITLE
(Ash.Error.Unknown) Unknown Error - unsupported expression in manual update action

### ISSUE THREAD

**Issue by ahey** [ash-project/ash#894]
I have a manual update action on my resource:

```elixir
defmodule Ht.Training.Card.Actions.Archive do
  use Ash.Resource.ManualUpdate

  require Ash.Query

  def update(changeset, _opts, context) do
    opts = Ht.Util.manual_action_opts(context)

    card =
      changeset.data
      |> archive_card(opts)
      |> invalidate_in_progress_certifications(opts)

    {:ok, card}
  end

  defp archive_card(card, opts) do
    card
    |> Ash.Changeset.new()
    |> Ash.Changeset.for_update(:update, opts)
    |> Ash.Changeset.force_change_attribute(:archived_at, DateTime.utc_now())
    |> Ht.Training.update!(opts)
  end

  defp invalidate_in_progress_certifications(card, opts) do
    # ...
  end
end
```

As of [this commit in ash](https://github.com/ash-project/ash/commit/dcbccec7c36e2cad9d8366fa797b617e043b7b28), the following error occurs when performing the manual action:

```
 1) test archive (Ht.Training.CardTest)
     test/ht/api/training/resources/training_card_test.exs:129
     ** (Ash.Error.Unknown) Unknown Error

     * ** (Ecto.QueryError) unsupported expression: {:id, "be2c4cb5-b1cd-442b-88ce-dec9c86cf4a4"} in query:

     from t0 in Ht.Training.TemplateVersion,
       as: 0,
       where: [id: "be2c4cb5-b1cd-442b-88ce-dec9c86cf4a4"],
       where: parent_as(0).template_version_id == t0.id,
       select: %{result: 1}

       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:1894: Ecto.Adapters.Postgres.Connection.error!/2
       (elixir 1.16.0) lib/enum.ex:4381: Enum.map_intersperse_list/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:1006: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:828: Ecto.Adapters.Postgres.Connection.paren_expr/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:805: Ecto.Adapters.Postgres.Connection.boolean/4
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:168: Ecto.Adapters.Postgres.Connection.all/2
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:887: Ecto.Adapters.Postgres.Connection.expr/3
       (elixir 1.16.0) lib/enum.ex:4381: Enum.map_intersperse_list/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:987: Ecto.Adapters.Postgres.Connection.expr/3
       (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
       (elixir 1.16.0) lib/enum.ex:1700: Enum."-map/2-lists^map/1-1-"/2
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:895: Ecto.Adapters.Postgres.Connection.expr/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:828: Ecto.Adapters.Postgres.Connection.paren_expr/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:807: anonymous fn/4 in Ecto.Adapters.Postgres.Connection.boolean/4
       (elixir 1.16.0) lib/enum.ex:2528: Enum."-reduce/3-lists^foldl/2-0-"/3
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:805: Ecto.Adapters.Postgres.Connection.boolean/4
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres/connection.ex:203: Ecto.Adapters.Postgres.Connection.update_all/2
       (ecto_sql 3.11.1) lib/ecto/adapters/postgres.ex:132: Ecto.Adapters.Postgres.prepare/2
       (ecto 3.11.1) lib/ecto/query/planner.ex:182: Ecto.Query.Planner.query_without_cache/4
       (ecto 3.11.1) lib/ecto/query/planner.ex:152: Ecto.Query.Planner.query_prepare/6
     stacktrace:
       (elixir 1.16.0) lib/process.ex:860: Process.info/2
       (ash 2.18.1) lib/ash/error/exception.ex:59: Ash.Error.Unknown."exception (overridable 2)"/1
       (ash 2.18.1) lib/ash/error/error.ex:600: Ash.Error.choose_error/2
       (ash 2.18.1) lib/ash/error/error.ex:260: Ash.Error.to_error_class/2
       (ash 2.18.1) lib/ash/actions/update/bulk.ex:462: Ash.Actions.Update.Bulk.do_atomic_update/5
       (ash 2.18.1) lib/ash/actions/update/bulk.ex:166: Ash.Actions.Update.Bulk.run/6
       (ash 2.18.1) lib/ash/actions/update/update.ex:103: Ash.Actions.Update.run/4
       (ash 2.18.1) lib/ash/api/api.ex:2879: Ash.Api.update!/3
       (heretask 0.1.0) lib/ht/api/training/resources/card/actions/archive.ex:11: Ht.Training.Card.Actions.Archive.update/3
       (ash 2.18.1) lib/ash/actions/update/update.ex:370: anonymous fn/5 in Ash.Actions.Update.commit/3
       (ash 2.18.1) lib/ash/changeset/changeset.ex:2823: Ash.Changeset.run_around_actions/2
       (ash 2.18.1) lib/ash/changeset/changeset.ex:2406: anonymous fn/3 in Ash.Changeset.with_hooks/3
       (ecto_sql 3.11.1) lib/ecto/adapters/sql.ex:1358: anonymous fn/3 in Ecto.Adapters.SQL.checkout_or_transaction/4
       (db_connection 2.6.0) lib/db_connection.ex:1710: DBConnection.run_transaction/4
       (ash 2.18.1) lib/ash/changeset/changeset.ex:2404: anonymous fn/3 in Ash.Changeset.with_hooks/3
       (ash 2.18.1) lib/ash/changeset/changeset.ex:2543: anonymous fn/2 in Ash.Changeset.transaction_hooks/2
       (ash 2.18.1) lib/ash/changeset/changeset.ex:2385: Ash.Changeset.with_hooks/3
       (ash 2.18.1) lib/ash/actions/update/update.ex:327: Ash.Actions.Update.commit/3
       (ash 2.18.1) lib/ash/actions/update/update.ex:202: Ash.Actions.Update.do_run/4
       (ash 2.18.1) lib/ash/actions/update/update.ex:161: Ash.Actions.Update.run/4
```

I isolated it to [this specific line in the most recent ash commit](https://github.com/ash-project/ash/commit/dcbccec7c36e2cad9d8366fa797b617e043b7b28#diff-00e1467061b21cc8d9b9524139ac565b4579bdc9c918fa13ca6fae90331f9d24R112). If I comment out that line the test passes again.

`authorize_changeset_with: :error`

The other aspect, is that there is an update policy that applies to the update. If I take this out of the equation, the test passes.

```elixir
policy action_type([:read, :update, :destroy]) do
  authorize_if relates_to_actor_via(
                  [
                    :template_version,
                    :template,
                    :org,
                    :active_accounts,
                    :user
                  ],
                  field: :user
                )
end
```

I tried replacing the `relates_to_actor_via` with an expression:

```elixir
authorize_if expr(
               template_version.template.org_id ==
                 ^actor([:user, :accounts, :org, :id])
             )
```

however this gives me this error (which I don't understand):

```
Scenario must pass strict check only, meaning `runtime` policies cannot be checked.

     This requirement is generally used for filtering on related resources, when we can't fetch those
     related resources to run `runtime` policies. For this reason, you generally want your primary read
     actions on your resources to have standard policies which can be checked statically (like `actor_attribute_equals`)
```

**Comment by zachdaniel** [comment]
This should be fixed in main.

**Comment by ahey** [comment]
Thanks, that has resolve the issue.
