### ISSUE TITLE
'Updates & Validations' section in 'get started' guide contains no validations.

### ISSUE THREAD

**Issue by chrishop** [ash-project/ash#930]
Cannot understate what a minor nitpick this is.
Putting it down here so its not missed.
This issue is what it says in the title.
Can either add an explicit validator to the section, or make a new section explaining the validator separately.

Found here: https://ash-hq.org/docs/guides/ash/2.5.0-rc.6/tutorials/get-started#updates-and-validations

**Comment by WurmPeter** [comment]
In v3.4.49 there is ```validate attribute_does_not_equal``` which is imho enough for a getting-started guide.

But maybe add it to the "Try out opening and closing a ticket"-part (trying to close the ticket a second time which should fail because of the validation).

If yes, I can do that.

**Comment by zachdaniel** [comment]
Sounds great 👍

**Comment by WurmPeter** [comment]
So when I try to close that ticket a second time, the application halts with an error. It this supposed to happen? 
```
...(3)> |>  (ticket
...(3)> |> Ash.Changeset.for_update(:close)
...(3)> |> Ash.update!())
```
results in
```
[debug] QUERY ERROR source="tickets" db=30.6ms queue=0.1ms idle=1621.5ms
UPDATE "tickets" AS t0 SET "status" = $1, "id" = (CASE WHEN t0."status"::varchar = $2::varchar THEN ash_raise_error(jsonb_build_object('exception', $3::text, 'input', jsonb_build_object($4::text, $5::jsonb, $6::text, $7::varchar::varchar, $8::text, $9::jsonb, $10::text, $11::jsonb))::jsonb, NULL::uuid) ELSE t0."id"::uuid END)::uuid WHERE (t0."id"::uuid = $12::uuid) RETURNING t0."id", t0."subject", t0."status", t0."representative_id" [:closed, :closed, "Ash.Error.Changes.InvalidAttribute", "message", "Ticket is already closed", "value", :closed, "vars", %{value: :closed, field: :status}, "field", "status", "9603c7b5-4864-46f0-bf38-6261fef91b96"]
↳ AshPostgres.DataLayer.update_query/4, at: lib/data_layer.ex:1429
** (Ash.Error.Invalid) 
Bread Crumbs:
  > Returned from bulk query update: Helpdesk.Support.Ticket.close

Invalid Error

* Invalid value provided for status: Ticket is already closed.

"closed"

  (ash 3.4.49) lib/ash/error/changes/invalid_attribute.ex:4: Ash.Error.Changes.InvalidAttribute.exception/1
  (ash_postgres 2.4.20) lib/data_layer.ex:2230: AshPostgres.DataLayer.handle_raised_error/4
  (ash 3.4.49) lib/ash/actions/update/bulk.ex:573: Ash.Actions.Update.Bulk.do_atomic_update/5
  (ash 3.4.49) lib/ash/actions/update/bulk.ex:272: Ash.Actions.Update.Bulk.run/6
  (ash 3.4.49) lib/ash/actions/update/update.ex:158: Ash.Actions.Update.run/4
  (ash 3.4.49) lib/ash.ex:2663: Ash.update/3
  (ash 3.4.49) lib/ash.ex:2603: Ash.update!/3
  (elixir 1.18.1) src/elixir.erl:386: :elixir.eval_external_handler/3
  (stdlib 6.0.1) erl_eval.erl:904: :erl_eval.do_apply/7
  (elixir 1.18.1) src/elixir.erl:364: :elixir.eval_forms/4
  (elixir 1.18.1) lib/module/parallel_checker.ex:120: Module.ParallelChecker.verify/1
  (iex 1.18.1) lib/iex/evaluator.ex:336: IEx.Evaluator.eval_and_inspect/3
  (iex 1.18.1) lib/iex/evaluator.ex:310: IEx.Evaluator.eval_and_inspect_parsed/3
  (iex 1.18.1) lib/iex/evaluator.ex:299: IEx.Evaluator.parse_eval_inspect/4
  (iex 1.18.1) lib/iex/evaluator.ex:189: IEx.Evaluator.loop/1
  (iex 1.18.1) lib/iex/evaluator.ex:34: IEx.Evaluator.init/5
  (stdlib 6.0.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
    (ash 3.4.49) lib/ash/error/invalid.ex:3: Ash.Error.Invalid.exception/1
    (ash 3.4.49) /home/nefcairon/elixir/tryouts/helpdesk/deps/splode/lib/splode.ex:264: Ash.Error.to_class/2
    (ash 3.4.49) lib/ash/error/error.ex:108: Ash.Error.to_error_class/2
    (ash 3.4.49) lib/ash/actions/update/bulk.ex:768: Ash.Actions.Update.Bulk.do_atomic_update/5
    (ash 3.4.49) lib/ash/actions/update/bulk.ex:272: Ash.Actions.Update.Bulk.run/6
    (ash 3.4.49) lib/ash/actions/update/update.ex:158: Ash.Actions.Update.run/4
    (ash 3.4.49) lib/ash.ex:2663: Ash.update/3
    (ash 3.4.49) lib/ash.ex:2603: Ash.update!/3
    iex:5: (file)
    ```

**Comment by zachdaniel** [comment]
Using the ! version, the function will raise. Validations wouldn't be too useful if they didn't prevent the operation from continuing. If you use `Ash.update` instead, it will return the error instead of raising it

**Comment by WurmPeter** [comment]
@zachdaniel What do think of this:


------

What if we would try to close the ticket again?

```elixir
ticket
|> Ash.Changeset.for_update(:close)
|> Ash.update()
```
Note that this time we use the version of update/1 without the ! as it won't raise an error. Instead it returns an error tuple with a %Ash.Error.Invalid struct that contains the 'Ticket is already closed' message defined in the ```attribute_does_not_equal``` validation:

```text
{:error,
 %Ash.Error.Invalid{
...
       message: "Ticket is already closed",
...
```

Is this ash-doc'y enough?

**Comment by zachdaniel** [comment]
That would be fine, although it should also be fine to just let the exception get raised to show the error. Why not let it raise? You could even show both?

**Comment by WurmPeter** [comment]
New version:


What if we would try to close the ticket again?

```elixir
ticket
|> Ash.Changeset.for_update(:close)
|> Ash.update!()
```

The application would halt with an error:

```text
...
** (Ash.Error.Invalid)
Bread Crumbs:
  > Returned from bulk query update: Helpdesk.Support.Ticket.close

Invalid Error

* Invalid value provided for status: Ticket is already closed.
...
```

Note the 'Ticket is already closed' message that we have defined in the ```attribute_does_not_equal``` validation.

And if we'd use the non-bang version:  

```elixir
ticket
|> Ash.Changeset.for_update(:close)
|> Ash.update()
```
we get an error tuple with a %Ash.Error.Invalid struct that contains the message:

```text
{:error,
 %Ash.Error.Invalid{
...
       message: "Ticket is already closed",
...
```

**Comment by zachdaniel** [comment]
Looks great!

**Comment by WurmPeter** [comment]
submitted PR in https://github.com/ash-project/ash/pull/1693
